#!/usr/bin/env python3
"""Generate curated, data-backed SEO guides from the official catalog."""

from __future__ import annotations

import csv
import re
import statistics
from datetime import date
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parent.parent
GUIDE_DIR = ROOT / "guides"
REPORT_DIR = ROOT / "data" / "reports"
GENERATED_MARKER = "<!-- Generated by scripts/build_guides.py; do not edit directly. -->"
PUBLISHED = "2026-07-21"

COMPARISON_GUIDES = [
    {
        "slug": "lanshan-1-vs-lanshan-1-pro",
        "title": "Lanshan 1 vs Lanshan 1 Pro — Weight, Wall Design & Price",
        "description": "Compare the 3F UL Gear Lanshan 1 and Lanshan 1 Pro by trail weight, wall design, fabric and official price.",
        "eyebrow": "Solo trekking-pole tent comparison",
        "category": "tent",
        "product_ids": ["3f-ul-gear-lanshan-1", "3f-ul-gear-lanshan-1-pro"],
        "intro": (
            "The standard Lanshan 1 and Lanshan 1 Pro target the same solo "
            "ultralight buyer, but they make a different trade-off between a "
            "double-wall layout and lower packed weight."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the Pro starts about 230 g lighter by the catalog's representative weights.",
            "<strong>Construction:</strong> the standard model uses a removable double-wall layout; the Pro integrates the inner and fly to save material.",
            "<strong>Price:</strong> the standard model starts lower, while the Pro charges more for its lighter configuration.",
            "<strong>Decision:</strong> choose the standard model for a more conventional double-wall setup; choose the Pro when reducing carried weight matters more.",
        ],
    },
    {
        "slug": "lanshan-2-vs-lanshan-2-pro",
        "title": "Lanshan 2 vs Lanshan 2 Pro — Specs, Weight & Price",
        "description": "Lanshan 2 vs Lanshan 2 Pro: compare official trail weight, two-person capacity, wall design, fabric and price.",
        "eyebrow": "2-person trekking-pole tent comparison",
        "category": "tent",
        "product_ids": ["3f-ul-gear-lanshan-2", "3f-ul-gear-lanshan-2-pro"],
        "intro": (
            "Both models are budget two-person trekking-pole shelters. The "
            "standard Lanshan 2 prioritizes a separate inner, while the Pro "
            "reduces representative trail weight with a more integrated design."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the Pro is about 140 g lighter using the representative trail weights in the official catalog.",
            "<strong>Capacity:</strong> both are listed as two-person shelters.",
            "<strong>Fabric choice:</strong> the Pro listing offers SilNylon / SilPoly options; check the selected variant before buying.",
            "<strong>Decision:</strong> the standard Lanshan 2 suits buyers who want a separate inner; the Pro suits buyers prioritizing the lower listed trail weight.",
        ],
    },
    {
        "slug": "fire-maple-fms-300t-vs-hornet-ii",
        "title": "Fire Maple FMS-300T vs Hornet II — Weight, Stability & Price",
        "description": "Compare Fire Maple FMS-300T and Hornet II titanium backpacking stoves by weight, pot support design and official price.",
        "eyebrow": "Ultralight canister stove comparison",
        "category": "stove",
        "product_ids": [
            "fire-maple-300-t-ultralight-titanium-backpacking-stove",
            "fire-maple-hornet-ii-titanium-gas-stove",
        ],
        "intro": (
            "The FMS-300T and Hornet II are closely related titanium canister "
            "stoves. The 300T minimizes weight and price; the Hornet II adds a "
            "redesigned support platform for a small weight increase."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the catalog rounds the 300T to about 40 g and the Hornet II to about 50 g.",
            "<strong>Pot support:</strong> Fire Maple describes the Hornet II as the more stability-focused design.",
            "<strong>Price:</strong> the 300T has the lower official reference price in the current catalog.",
            "<strong>Decision:</strong> choose the 300T for minimum grams and cost; choose the Hornet II when its wider, redesigned supports are worth the small penalty.",
        ],
    },
    {
        "slug": "naturehike-tuye-r5-8-vs-r6-5-vs-r8-8",
        "title": "Naturehike TuYe R5.8 vs R6.5 vs R8.8 Sleeping Pads",
        "description": "Compare Naturehike TuYe R5.8, R6.5 and R8.8 sleeping pads by insulation, representative weight, design and price.",
        "eyebrow": "Cold-weather sleeping pad comparison",
        "category": "sleeping-pad",
        "product_ids": [
            "naturehike-tuye-r5-8-ultralight-inflatable-pad",
            "naturehike-tuye-r6-5-ultralight-inflatable-pad",
            "naturehike-tuye-r8-8-ultralight-inflatable-pad",
        ],
        "intro": (
            "The TuYe range uses the model name to signal insulation level. "
            "Higher R-value is not automatically better for every trip: it can "
            "also change price, thickness, size options and carried weight."
        ),
        "takeaways": [
            "<strong>R5.8:</strong> the lowest-cost option here and already positioned by Naturehike for cold-weather use.",
            "<strong>R6.5:</strong> adds reinforced sidewalls and sits between the other two models in insulation.",
            "<strong>R8.8:</strong> provides the highest stated insulation and the highest starting price.",
            "<strong>Variant warning:</strong> pad weights vary by shape and size; compare the exact selected variant on the official listing.",
        ],
    },
]

LIGHTWEIGHT_TENT_IDS = [
    "montbell-u-l-dome-shelter-2-yellow",
    "3f-ul-gear-lanshan-2-pro",
    "3f-ul-gear-lanshan-2",
    "asta-gear-astagear-pursuit-2-2-person-lightweight-silicone-coated-fast-setup-outdoor-camping-tent-windproof-waterproof-for-hiking-mountaineering",
    "asta-gear-astagear-vista-2-person-lightweight-tent-outdoor-hiking-camping-shelter-rainproof-wind-resistant",
    "naturehike-cloud-up-ul-2-person-ultralight-backpacking-tent",
    "naturehike-tagar-2-person-ultralight-backpacking-tent",
    "naturehike-daban-2-person-ultralight-4-season-tunnel-tent",
    "naturehike-star-trailtm-ext-2-person-ultralight-backpacking-tent",
    "naturehike-summiture-2-person-ultralight-backpacking-tent",
    "naturehike-cloud-up-ext-2-person-ultralight-backpacking-tent",
    "naturehike-star-river-ul-2-person-ultralight-backpacking-tent",
    "naturehike-star-rivertm-ext-2-person-ultralight-backpacking-tent",
    "fire-maple-tropics-2-person-backpacking-tent",
]

ACCESSORY_PATTERN = re.compile(
    r"\b(accessor|footprint|stuff sack|dry bag|peg|pole|inner tent|"
    r"groundsheet|connection|jack|pump|strap|repair|liner|blanket|"
    r"seat|pillow|cot|bench|table|chair)\b",
    re.IGNORECASE,
)


def guide_page_config(
    slug: str,
    title: str,
    description: str,
    priority: str = "0.7",
) -> dict:
    path = "/guides/" if slug == "index" else f"/guides/{slug}.html"
    file = "guides/index.html" if slug == "index" else f"guides/{slug}.html"
    return {
        "path": path,
        "file": file,
        "title": title,
        "description": description,
        "changefreq": "monthly",
        "priority": priority,
        "schema": "generated-guide",
    }


def article_schema(
    site_url: str,
    path: str,
    title: str,
    description: str,
    category_label: str = "Guides",
) -> dict:
    url = f"{site_url}{path}"
    return {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": f"{site_url}/",
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Guides",
                        "item": f"{site_url}/guides/",
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": category_label,
                        "item": url,
                    },
                ],
            },
            {
                "@type": "Article",
                "headline": title,
                "description": description,
                "url": url,
                "datePublished": PUBLISHED,
                "dateModified": date.today().isoformat(),
                "author": {
                    "@type": "Organization",
                    "name": "CampGear Compare",
                    "url": f"{site_url}/",
                },
                "publisher": {"@id": f"{site_url}/#organization"},
                "isPartOf": {"@id": f"{site_url}/#website"},
            },
        ],
    }


def page_shell(
    *,
    title: str,
    description: str,
    canonical: str,
    schema: dict,
    current_path: str,
    body: str,
    b: ModuleType,
) -> str:
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        f"{b.static_page_head(title, description, canonical, schema)}\n"
        '<body data-page="guide">\n'
        f"{b.static_header(current_path)}\n"
        f"{body}\n"
        f"{b.static_footer()}\n"
        f"{GENERATED_MARKER}\n"
        "</body>\n"
        "</html>\n"
    )


def product_name(product: dict, brands: dict[str, dict], b: ModuleType) -> str:
    brand_id = product.get("brandId", "")
    return (
        f"{b.brand_display_name(brands.get(brand_id), brand_id)} "
        f"{product.get('model', '')}"
    ).strip()


def comparison_value(product: dict, key: str, b: ModuleType) -> str:
    if key == "weight":
        return b.format_weight(product) or "Not listed"
    if key == "price":
        return b.format_price(product)
    if key == "capacity":
        return b.format_capacity_display(product) or "Not listed"
    return b.spec_value(product, key) or "Not listed"


def comparison_page(
    guide: dict,
    product_map: dict[str, dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
) -> str:
    products = [product_map[pid] for pid in guide["product_ids"]]
    slug = guide["slug"]
    path = f"/guides/{slug}.html"
    canonical = f"{site_url}{path}"
    names = [product_name(p, brands, b) for p in products]
    category_path = b.category_page_path(guide["category"])
    category_name = b.category_label(guide["category"])

    spec_rows = [
        ("Weight", "weight"),
        ("Capacity", "capacity"),
        ("R-Value", "rValue"),
        ("Type / Structure", "structure"),
        ("Fabric", "fabric"),
        ("Reference Price", "price"),
    ]
    header = "".join(
        f'<th scope="col"><a href="{b.escape_html(b.product_path(p))}">'
        f"{b.escape_html(name)}</a></th>"
        for p, name in zip(products, names)
    )
    rows = []
    for label, key in spec_rows:
        values = [comparison_value(p, key, b) for p in products]
        if key not in {"weight", "price"} and all(v == "Not listed" for v in values):
            continue
        rows.append(
            f'<tr><th scope="row">{b.escape_html(label)}</th>'
            + "".join(f"<td>{b.escape_html(value)}</td>" for value in values)
            + "</tr>"
        )

    source_links = " · ".join(
        f'<a href="{b.escape_html(p.get("sourceUrl", ""))}" '
        f'rel="noopener noreferrer" target="_blank">{b.escape_html(name)} official listing</a>'
        for p, name in zip(products, names)
        if p.get("sourceUrl")
    )
    takeaways = "".join(f"<li>{item}</li>" for item in guide["takeaways"])
    product_links = "".join(
        f'<li><a href="{b.escape_html(b.product_path(p))}">'
        f"{b.escape_html(name)} — full specs</a></li>"
        for p, name in zip(products, names)
    )
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        f"    <span>{b.escape_html(guide['title'])}</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        f'      <p class="page__eyebrow">{b.escape_html(guide["eyebrow"])}</p>\n'
        f'      <h1 class="page__title">{b.escape_html(guide["title"].split(" — ")[0])}</h1>\n'
        f'      <p class="page__lead">{b.escape_html(guide["intro"])}</p>\n'
        '      <div class="static-actions">\n'
        f'        <a class="static-button static-button--primary" href="{b.escape_html(category_path)}">'
        f"Open full {b.escape_html(category_name.lower())} table</a>\n"
        "      </div>\n"
        "    </header>\n"
        '    <section class="static-panel" aria-labelledby="spec-table">\n'
        '      <h2 id="spec-table">Official specs side by side</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        f'        <thead><tr><th scope="col">Spec</th>{header}</tr></thead>\n'
        f"        <tbody>{''.join(rows)}</tbody>\n"
        "      </table></div>\n"
        f'      <p class="page__lead page__lead--compact">Sources: {source_links}</p>\n'
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="takeaways">\n'
        '      <h2 id="takeaways">How to choose</h2>\n'
        f'      <ul class="static-link-list">{takeaways}</ul>\n'
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Method and limitations</h2>\n'
        "      <p>This is a specification comparison, not a hands-on review. "
        "Weights and prices can vary by size, fabric, season and market. We use "
        "representative values from brand listings and link the source so you "
        "can verify the exact variant before buying.</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="related-products">\n'
        '      <h2 id="related-products">Full product pages</h2>\n'
        f'      <ul class="static-link-list">{product_links}</ul>\n'
        f'      <p><a href="/guides/">Browse all data-backed guides</a> · '
        f'<a href="{b.escape_html(category_path)}">Compare all {b.escape_html(category_name.lower())}</a></p>\n'
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    schema = article_schema(
        site_url, path, guide["title"], guide["description"], guide["eyebrow"]
    )
    return page_shell(
        title=guide["title"],
        description=guide["description"],
        canonical=canonical,
        schema=schema,
        current_path=category_path,
        body=body,
        b=b,
    )


def lightweight_tents_page(
    product_map: dict[str, dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
) -> tuple[dict, str]:
    slug = "2-person-backpacking-tents-under-2kg"
    title = "2-Person Backpacking Tents Under 2 kg — 14 Models Compared"
    description = (
        "Compare 14 two-person backpacking tents under 2 kg by listed weight, "
        "structure and official reference price."
    )
    page = guide_page_config(slug, title, description)
    products = [product_map[pid] for pid in LIGHTWEIGHT_TENT_IDS]
    products.sort(key=lambda p: (b.parse_weight_kg(p) or 99, b.parse_price(p) or 99999))
    rows = []
    for product in products:
        brand_id = product.get("brandId", "")
        brand = b.brand_display_name(brands.get(brand_id), brand_id)
        rows.append(
            "<tr>"
            f"<td>{b.escape_html(brand)}</td>"
            f'<td><a href="{b.escape_html(b.product_path(product))}">'
            f"{b.escape_html(product.get('model', ''))}</a></td>"
            f"<td>{b.escape_html(b.format_weight(product) or 'Not listed')}</td>"
            f"<td>{b.escape_html(b.spec_value(product, 'structure') or 'Not listed')}</td>"
            f"<td>{b.escape_html(b.format_price(product))}</td>"
            "</tr>"
        )
    path = page["path"]
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        "    <span>2-person tents under 2 kg</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        '      <p class="page__eyebrow">Weight-filtered tent shortlist</p>\n'
        '      <h1 class="page__title">2-Person Backpacking Tents Under 2 kg</h1>\n'
        "      <p class=\"page__lead\">A curated shortlist of complete two-person "
        "shelters whose representative listed weight is no more than 2 kg. "
        "Accessories, inner tents and records with conflicting capacities were "
        "removed manually.</p>\n"
        "    </header>\n"
        '    <section class="static-panel" aria-labelledby="shortlist">\n'
        '      <h2 id="shortlist">14 models, lightest first</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        "        <thead><tr><th>Brand</th><th>Model</th><th>Weight</th>"
        "<th>Structure</th><th>Price</th></tr></thead>\n"
        f"        <tbody>{''.join(rows)}</tbody>\n"
        "      </table></div>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="how-to-read">\n'
        '      <h2 id="how-to-read">How to use this shortlist</h2>\n'
        "      <ul class=\"static-link-list\">"
        "<li><strong>Check the weight basis:</strong> trail, minimum and packaged weights are not always equivalent.</li>"
        "<li><strong>Check the variant:</strong> fabric and inner-tent choices can change total weight.</li>"
        "<li><strong>Check support requirements:</strong> trekking-pole shelters may exclude the poles from listed weight.</li>"
        "<li><strong>Use price as a reference:</strong> currencies, promotions and stock change over time.</li>"
        "</ul>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Methodology</h2>\n'
        "      <p>We filtered the CampGear Compare official-source catalog for "
        "two-person tents with a positive representative weight at or below "
        "2.0 kg, then manually removed accessories and records whose model name "
        "conflicted with the capacity field. This is a spec shortlist, not a "
        "hands-on ranking.</p>\n"
        '      <p><a href="/tent.html">Compare all tents</a> · '
        '<a href="/guides/">Browse all guides</a></p>\n'
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    html = page_shell(
        title=title,
        description=description,
        canonical=f"{site_url}{path}",
        schema=article_schema(site_url, path, title, description, "Lightweight tents"),
        current_path="/tent.html",
        body=body,
        b=b,
    )
    return page, html


def clean_report_rows(products: list[dict], category: str, b: ModuleType) -> list[dict]:
    rows = []
    for product in products:
        if product.get("category") != category:
            continue
        if product.get("inSummaryTable") is False:
            continue
        if ACCESSORY_PATTERN.search(product.get("model", "")):
            continue
        weight = b.parse_weight_kg(product)
        price = b.parse_price(product)
        if weight is None or weight <= 0 or price is None or price <= 0:
            continue
        rows.append(product)
    return rows


def data_report_page(
    products: list[dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
) -> tuple[dict, str]:
    slug = "camping-gear-weight-price-report-2026"
    categories = ["tent", "tarp", "sleeping-bag", "sleeping-pad", "stove"]
    stats = []
    report_rows: list[dict] = []
    total = 0
    for category in categories:
        rows = clean_report_rows(products, category, b)
        report_rows.extend(rows)
        total += len(rows)
        weights = sorted(b.parse_weight_kg(p) for p in rows)
        prices = sorted(b.parse_price(p) for p in rows)
        stats.append(
            {
                "category": category,
                "count": len(rows),
                "brands": len({p.get("brandId") for p in rows}),
                "median_weight": statistics.median(weights),
                "median_price": statistics.median(prices),
                "under_1kg": sum(weight <= 1 for weight in weights),
                "under_200": sum(price <= 200 for price in prices),
            }
        )
    title = f"Camping Gear Weight & Price Report 2026 — {total} Products"
    description = (
        f"Original analysis of {total} tents, tarps, sleeping bags, pads and "
        "stoves: median weight, price and lightweight product counts."
    )
    page = guide_page_config(slug, title, description, "0.8")
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / "camping-gear-weight-price-2026.csv"
    with report_path.open("w", encoding="utf-8", newline="") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(
            [
                "category",
                "brand",
                "model",
                "weight_kg",
                "reference_price",
                "currency",
                "product_url",
                "official_source",
            ]
        )
        for product in sorted(
            report_rows,
            key=lambda p: (
                p.get("category", ""),
                p.get("brandId", ""),
                p.get("model", ""),
            ),
        ):
            brand_id = product.get("brandId", "")
            writer.writerow(
                [
                    product.get("category", ""),
                    b.brand_display_name(brands.get(brand_id), brand_id),
                    product.get("model", ""),
                    b.parse_weight_kg(product),
                    b.parse_price(product),
                    product.get("currency", "USD"),
                    f"{site_url}{b.product_path(product)}",
                    product.get("sourceUrl", ""),
                ]
            )
    rows_html = "".join(
        "<tr>"
        f"<td>{b.escape_html(b.category_label(row['category']))}</td>"
        f"<td>{row['count']}</td>"
        f"<td>{row['brands']}</td>"
        f"<td>{row['median_weight']:.2f} kg</td>"
        f"<td>{row['median_price']:.2f} USD*</td>"
        f"<td>{row['under_1kg']}</td>"
        f"<td>{row['under_200']}</td>"
        "</tr>"
        for row in stats
    )
    path = page["path"]
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        "    <span>2026 weight and price report</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        '      <p class="page__eyebrow">Original catalog analysis · July 2026</p>\n'
        '      <h1 class="page__title">Camping Gear Weight &amp; Price Report 2026</h1>\n'
        f'      <p class="page__lead">We analyzed {total} product records with '
        "usable weight and price data across five camping categories. The result "
        "is a transparent benchmark for comparing a product with its category.</p>\n"
        '      <div class="static-actions"><a class="static-button static-button--primary" '
        'href="/data/reports/camping-gear-weight-price-2026.csv" download>'
        "Download the cleaned CSV</a></div>\n"
        "    </header>\n"
        '    <section class="static-panel" aria-labelledby="results">\n'
        '      <h2 id="results">Category benchmarks</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        "        <thead><tr><th>Category</th><th>Products</th><th>Brands</th>"
        "<th>Median Weight</th><th>Median Price</th><th>≤ 1 kg</th><th>≤ $200</th></tr></thead>\n"
        f"        <tbody>{rows_html}</tbody>\n"
        "      </table></div>\n"
        "      <p class=\"page__lead page__lead--compact\">*Reference prices are "
        "normalized only by their stored numeric value; most records are USD, "
        "but a small number of other-market records may use another currency. "
        "Use medians directionally, not as exchange-rate-adjusted market prices.</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="findings">\n'
        '      <h2 id="findings">What the data shows</h2>\n'
        "      <ul class=\"static-link-list\">"
        f"<li><strong>Tents:</strong> {stats[0]['count']} clean records have a median representative weight of {stats[0]['median_weight']:.2f} kg.</li>"
        f"<li><strong>Sleeping bags:</strong> {stats[2]['under_1kg']} of {stats[2]['count']} records weigh 1 kg or less.</li>"
        f"<li><strong>Sleeping pads:</strong> {stats[3]['under_200']} of {stats[3]['count']} records list a reference price at or below 200.</li>"
        f"<li><strong>Stoves:</strong> the median representative weight is {stats[4]['median_weight']:.2f} kg in the cleaned sample.</li>"
        "</ul>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Reproducible methodology</h2>\n'
        "      <p>Source data comes from brand product pages in the public "
        "CampGear Compare catalog. We included visible records with positive "
        "weight and price values, then excluded model names that clearly describe "
        "accessories such as footprints, stuff sacks, pumps, repair parts and "
        "inner tents. Medians reduce the influence of unusually large or premium "
        "products. The report is regenerated by <code>scripts/build_guides.py</code>.</p>\n"
        "      <p>Download or inspect the source records through the site's "
        '<a href="/about.html">methodology page</a>, use the '
        '<a href="/data/reports/camping-gear-weight-price-2026.csv" download>cleaned CSV</a>, '
        "and verify individual values "
        "using the official source link on every product page.</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="explore">\n'
        '      <h2 id="explore">Explore the underlying catalog</h2>\n'
        '      <ul class="static-link-list">'
        '<li><a href="/tent.html">Tent comparison table</a></li>'
        '<li><a href="/sleeping-bag.html">Sleeping bag comparison table</a></li>'
        '<li><a href="/sleeping-pad.html">Sleeping pad comparison table</a></li>'
        '<li><a href="/tarp.html">Tarp comparison table</a></li>'
        '<li><a href="/stove.html">Stove comparison table</a></li>'
        "</ul>\n"
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    schema = article_schema(site_url, path, title, description, "Data report")
    schema["@graph"].append(
        {
            "@type": "Dataset",
            "name": "CampGear Compare Weight and Price Dataset 2026",
            "description": description,
            "url": f"{site_url}{path}",
            "datePublished": PUBLISHED,
            "dateModified": date.today().isoformat(),
            "creator": {
                "@type": "Organization",
                "name": "CampGear Compare",
                "url": f"{site_url}/",
            },
            "variableMeasured": [
                "Product category",
                "Brand",
                "Representative weight in kilograms",
                "Reference price",
                "Currency",
            ],
            "distribution": {
                "@type": "DataDownload",
                "encodingFormat": "text/csv",
                "contentUrl": (
                    f"{site_url}/data/reports/"
                    "camping-gear-weight-price-2026.csv"
                ),
            },
        }
    )
    html = page_shell(
        title=title,
        description=description,
        canonical=f"{site_url}{path}",
        schema=schema,
        current_path="",
        body=body,
        b=b,
    )
    return page, html


def guides_index_page(
    pages: list[dict],
    site_url: str,
    b: ModuleType,
) -> tuple[dict, str]:
    title = "Camping Gear Guides & Data Reports | CampGear Compare"
    description = (
        "Data-backed camping gear comparisons, lightweight shortlists and "
        "original weight and price reports using official product specs."
    )
    page = guide_page_config("index", title, description, "0.8")
    links = "".join(
        '<section class="static-panel">'
        f'<h2><a href="{b.escape_html(item["path"])}">{b.escape_html(item["title"])}</a></h2>'
        f'<p>{b.escape_html(item["description"])}</p>'
        "</section>"
        for item in pages
    )
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>'
        "    <span>Guides</span>\n"
        "  </nav>\n"
        '  <header class="page__head">\n'
        '    <p class="page__eyebrow">Official specs, explained</p>\n'
        '    <h1 class="page__title">Camping Gear Guides &amp; Data Reports</h1>\n'
        "    <p class=\"page__lead\">Focused comparisons and original catalog "
        "analysis. These pages organize official specifications; they do not "
        "claim hands-on testing.</p>\n"
        "  </header>\n"
        f"{links}\n"
        "</main>"
    )
    schema = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": title,
        "description": description,
        "url": f"{site_url}/guides/",
        "mainEntity": {
            "@type": "ItemList",
            "numberOfItems": len(pages),
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": index,
                    "name": item["title"],
                    "url": f"{site_url}{item['path']}",
                }
                for index, item in enumerate(pages, start=1)
            ],
        },
    }
    html = page_shell(
        title=title,
        description=description,
        canonical=f"{site_url}/guides/",
        schema=schema,
        current_path="",
        body=body,
        b=b,
    )
    return page, html


def build_guides(
    site_url: str,
    products: list[dict],
    brands: dict[str, dict],
    b: ModuleType,
) -> list[dict]:
    GUIDE_DIR.mkdir(exist_ok=True)
    product_map = {product.get("id"): product for product in products}
    pages: list[dict] = []

    for guide in COMPARISON_GUIDES:
        missing = [pid for pid in guide["product_ids"] if pid not in product_map]
        if missing:
            raise ValueError(f"{guide['slug']}: missing product IDs: {missing}")
        page = guide_page_config(
            guide["slug"], guide["title"], guide["description"]
        )
        (GUIDE_DIR / f"{guide['slug']}.html").write_text(
            comparison_page(guide, product_map, brands, site_url, b),
            encoding="utf-8",
        )
        pages.append(page)

    missing_tents = [pid for pid in LIGHTWEIGHT_TENT_IDS if pid not in product_map]
    if missing_tents:
        raise ValueError(f"lightweight tent guide: missing product IDs: {missing_tents}")
    page, html = lightweight_tents_page(product_map, brands, site_url, b)
    (GUIDE_DIR / "2-person-backpacking-tents-under-2kg.html").write_text(
        html, encoding="utf-8"
    )
    pages.append(page)

    page, html = data_report_page(products, brands, site_url, b)
    (GUIDE_DIR / "camping-gear-weight-price-report-2026.html").write_text(
        html, encoding="utf-8"
    )
    pages.append(page)

    existing_page = guide_page_config(
        "snow-peak-amenity-dome-2-vs-naturehike-cloud-up-2",
        "Snow Peak Amenity Dome 2 vs Naturehike Cloud Up 2",
        "A 2-person car-camping tent compared with a lighter budget backpacking tent.",
    )
    index_page, index_html = guides_index_page(
        [existing_page, *pages], site_url, b
    )
    (GUIDE_DIR / "index.html").write_text(index_html, encoding="utf-8")
    return [index_page, *pages]


def main() -> int:
    import build_sitemap as b

    seo = b.load_json(b.SEO_PATH)
    site_url = seo["siteUrl"].rstrip("/")
    brands_data = b.load_json(b.DATA / "brands.json")
    brands = b.brand_map(brands_data if isinstance(brands_data, list) else [])
    products = b.load_official_products()
    pages = build_guides(site_url, products, brands, b)
    print(f"Generated {len(pages)} guide page(s) in {GUIDE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

