#!/usr/bin/env python3
"""Generate curated, data-backed SEO guides from the official catalog."""

from __future__ import annotations

import csv
import json
import re
import statistics
from datetime import date
from pathlib import Path
from types import ModuleType
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
GUIDE_DIR = ROOT / "guides"
REPORT_DIR = ROOT / "data" / "reports"
GUIDE_APPROVALS_PATH = ROOT / "data" / "guide-approvals.json"
GENERATED_MARKER = "<!-- Generated by scripts/build_guides.py; do not edit directly. -->"
PUBLISHED = "2026-07-21"
DEFAULT_GUIDE_MODIFIED = "2026-08-05"
LIGHTWEIGHT_TENTS_REVIEWED = "2026-08-05T23:57:11+08:00"
WEIGHT_PRICE_REPORT_REVIEWED = "2026-08-15"

COMPARISON_GUIDES = [
    {
        "slug": "lanshan-1-vs-lanshan-1-pro",
        "title": "Lanshan 1 vs Lanshan 1 Pro — Weight, Wall Design & Price",
        "description": "Compare the 3F UL Gear Lanshan 1 and Lanshan 1 Pro by trail weight, wall design, fabric and official price.",
        "eyebrow": "Solo trekking-pole tent comparison",
        "category": "tent",
        "product_ids": ["3f-ul-gear-lanshan-1", "3f-ul-gear-lanshan-1-pro"],
        "intro": (
            "The standard Lanshan 1 and Lanshan 1 Pro target the same solo "
            "ultralight buyer, but they make a different trade-off between a "
            "double-wall layout and lower packed weight."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the Pro starts about 230 g lighter by the catalog's representative weights.",
            "<strong>Construction:</strong> the standard model uses a removable double-wall layout; the Pro integrates the inner and fly to save material.",
            "<strong>Price:</strong> the standard model starts lower, while the Pro charges more for its lighter configuration.",
            "<strong>Decision:</strong> choose the standard model for a more conventional double-wall setup; choose the Pro when reducing carried weight matters more.",
        ],
    },
    {
        "slug": "lanshan-2-vs-lanshan-2-pro",
        "title": "Lanshan 2 vs Lanshan 2 Pro — Specs, Weight & Price",
        "description": "Lanshan 2 vs Lanshan 2 Pro: compare official trail weight, two-person capacity, wall design, fabric and price.",
        "eyebrow": "2-person trekking-pole tent comparison",
        "category": "tent",
        "product_ids": ["3f-ul-gear-lanshan-2", "3f-ul-gear-lanshan-2-pro"],
        "intro": (
            "Both models are budget two-person trekking-pole shelters. The "
            "standard Lanshan 2 prioritizes a separate inner, while the Pro "
            "reduces representative trail weight with a more integrated design."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the Pro is about 140 g lighter using the representative trail weights in the official catalog.",
            "<strong>Capacity:</strong> both are listed as two-person shelters.",
            "<strong>Fabric choice:</strong> the Pro listing offers SilNylon / SilPoly options; check the selected variant before buying.",
            "<strong>Decision:</strong> the standard Lanshan 2 suits buyers who want a separate inner; the Pro suits buyers prioritizing the lower listed trail weight.",
        ],
    },
    {
        "slug": "fire-maple-fms-300t-vs-hornet-ii",
        "title": "Fire Maple FMS-300T vs Hornet II — Weight, Stability & Price",
        "description": "Compare Fire Maple FMS-300T and Hornet II titanium backpacking stoves by weight, pot support design and official price.",
        "eyebrow": "Ultralight canister stove comparison",
        "category": "stove",
        "product_ids": [
            "fire-maple-300-t-ultralight-titanium-backpacking-stove",
            "fire-maple-hornet-ii-titanium-gas-stove",
        ],
        "intro": (
            "The FMS-300T and Hornet II are closely related titanium canister "
            "stoves. The 300T minimizes weight and price; the Hornet II adds a "
            "redesigned support platform for a small weight increase."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the catalog rounds the 300T to about 40 g and the Hornet II to about 50 g.",
            "<strong>Pot support:</strong> Fire Maple describes the Hornet II as the more stability-focused design.",
            "<strong>Price:</strong> the 300T has the lower official reference price in the current catalog.",
            "<strong>Decision:</strong> choose the 300T for minimum grams and cost; choose the Hornet II when its wider, redesigned supports are worth the small penalty.",
        ],
    },
    {
        "slug": "naturehike-tuye-r5-8-vs-r6-5-vs-r8-8",
        "title": "Naturehike TuYe R5.8 vs R6.5 vs R8.8 Sleeping Pads",
        "description": "Compare Naturehike TuYe R5.8, R6.5 and R8.8 sleeping pads by insulation, representative weight, design and price.",
        "eyebrow": "Cold-weather sleeping pad comparison",
        "category": "sleeping-pad",
        "product_ids": [
            "naturehike-tuye-r5-8-ultralight-inflatable-pad",
            "naturehike-tuye-r6-5-ultralight-inflatable-pad",
            "naturehike-tuye-r8-8-ultralight-inflatable-pad",
        ],
        "intro": (
            "The TuYe range uses the model name to signal insulation level. "
            "Higher R-value is not automatically better for every trip: it can "
            "also change price, thickness, size options and carried weight."
        ),
        "takeaways": [
            "<strong>R5.8:</strong> the lowest-cost option here and already positioned by Naturehike for cold-weather use.",
            "<strong>R6.5:</strong> adds reinforced sidewalls and sits between the other two models in insulation.",
            "<strong>R8.8:</strong> provides the highest stated insulation and the highest starting price.",
            "<strong>Variant warning:</strong> pad weights vary by shape and size; compare the exact selected variant on the official listing.",
        ],
    },
    {
        "slug": "naturehike-snowbird-sp700-vs-sp550",
        "title": "Naturehike Snowbird SP700 vs SP550 — Temperature, Weight & Price",
        "description": "Choose Snowbird SP700 for the lower 19°F label or SP550 for milder trips and a lower starting price; compare current weight, fill and price data.",
        "eyebrow": "Cold-weather down sleeping bag comparison",
        "category": "sleeping-bag",
        "product_ids": [
            "naturehike-snowbird-sp700-down-mummy-sleeping-bag",
            "naturehike-snowbirdtm-sp550-down-mummy-sleeping-bag-29-3-f-1-5-c",
        ],
        "intro": (
            "The Snowbird SP700 targets colder trips with more down and a lower "
            "temperature label, while the SP550 targets milder conditions at a "
            "lower starting price. Their current representative catalog weights "
            "are both about 1.2 kg, so warmth target matters more than model number."
        ),
        "verdict": (
            "Choose the SP700 when the colder 19°F / -7.3°C brand label is the "
            "priority. Choose the SP550 for milder 29.3°F / -1.5°C conditions "
            "and the lower $149.99 starting price. Current representative weights "
            "are both about 1.2 kg, so the SP550 has no clear normalized weight advantage."
        ),
        "reviewed_on": "2026-07-31",
        "limitations": (
            "This is a specification comparison, not a hands-on thermal test. The "
            "temperature figures are Naturehike model labels, not independently "
            "verified ISO comfort ratings. SP700 weight is the listed M-size value; "
            "other sizes and current prices can differ. Check the linked official "
            "variant before relying on a weight or temperature figure."
        ),
        "takeaways": [
            "<strong>Temperature label:</strong> the SP700 model is listed at 19°F / -7.3°C; the SP550 at 29.3°F / -1.5°C.",
            "<strong>Weight:</strong> current representative catalog weights are about 1.2 kg for both models; the SP700 figure is for M size.",
            "<strong>Insulation:</strong> both listings describe 650-fill-power duck down, but the model names represent different fill amounts and warmth targets.",
            "<strong>Price:</strong> SP700 currently spans $159–$199.99, while SP550 spans $149.99–$169.99; compare the exact size rather than only the starting price.",
            "<strong>Temperature warning:</strong> brand model labels are not interchangeable with independently tested ISO comfort ratings.",
        ],
    },
    {
        "slug": "naturehike-giling-pro-1-vs-mongar-pro-1",
        "title": "Naturehike Giling Pro 1 vs Mongar Pro 1 — Weight & Season",
        "description": "Choose Giling Pro 1 for four-season positioning or Mongar Pro 1 for a 230 g lighter three-season setup; compare structure and price.",
        "eyebrow": "Naturehike solo tent comparison",
        "category": "tent",
        "product_ids": [
            "naturehike-giling-protm-1-person-backpacking-tent",
            "naturehike-mongartm-pro-1-person-ultralight-backpacking-tent",
        ],
        "intro": (
            "These solo tents share the same current reference price but serve "
            "different use cases. Naturehike positions the Giling Pro for "
            "four-season protection and the lighter Mongar Pro for three-season trekking."
        ),
        "verdict": (
            "Choose the Giling Pro 1 for its four-season positioning, semi-solid "
            "inner and reinforced quick-pitch X-frame. Choose the Mongar Pro 1 for "
            "three-season trips when its roughly 230 g lower listed weight and "
            "freestanding double-wall layout are the better fit. Both currently list at $149."
        ),
        "reviewed_on": "2026-07-31",
        "limitations": (
            "This is a specification comparison, not a storm-worthiness test. "
            "Season labels describe Naturehike's intended positioning and do not "
            "guarantee performance in every winter or alpine condition. Listed "
            "weights and the $149 reference prices can change by variant or market; "
            "verify the linked official listings before purchase."
        ),
        "takeaways": [
            "<strong>Weight:</strong> the Mongar Pro is listed at about 1.97 kg, roughly 230 g lighter than the 2.2 kg Giling Pro.",
            "<strong>Season positioning:</strong> Naturehike markets the Giling Pro as a four-season model and the Mongar Pro for spring-through-fall use.",
            "<strong>Structure:</strong> the Giling Pro emphasizes an integrated quick-pitch X-frame; the Mongar Pro uses a freestanding double-wall layout.",
            "<strong>Price:</strong> both records currently carry the same $149 official reference price.",
            "<strong>Decision:</strong> choose from expected weather and structure first; the listed weight difference is secondary to the intended season.",
        ],
    },
]

LIGHTWEIGHT_TENT_IDS = [
    "montbell-u-l-dome-shelter-2-yellow",
    "3f-ul-gear-lanshan-2-pro",
    "3f-ul-gear-lanshan-2",
    "asta-gear-astagear-pursuit-2-2-person-lightweight-silicone-coated-fast-setup-outdoor-camping-tent-windproof-waterproof-for-hiking-mountaineering",
    "asta-gear-astagear-vista-2-person-lightweight-tent-outdoor-hiking-camping-shelter-rainproof-wind-resistant",
    "naturehike-cloud-up-ul-2-person-ultralight-backpacking-tent",
    "naturehike-tagar-2-person-ultralight-backpacking-tent",
    "naturehike-daban-2-person-ultralight-4-season-tunnel-tent",
    "naturehike-star-trailtm-ext-2-person-ultralight-backpacking-tent",
    "naturehike-summiture-2-person-ultralight-backpacking-tent",
    "naturehike-cloud-up-ext-2-person-ultralight-backpacking-tent",
    "naturehike-star-river-ul-2-person-ultralight-backpacking-tent",
    "naturehike-star-rivertm-ext-2-person-ultralight-backpacking-tent",
    "fire-maple-tropics-2-person-backpacking-tent",
]

COLLECTION_GUIDES = [
    {
        "slug": "naturehike-cloud-up-models-compared",
        "title": "Naturehike Cloud Up Tents Compared — 12 Models by Weight & Price",
        "description": "Compare 12 Naturehike Cloud Up, Base, Pro, UL and EXT tents by capacity, representative weight and official reference price.",
        "eyebrow": "Naturehike Cloud Up model guide",
        "category": "tent",
        "product_ids": [
            "naturehike-cloud-up-1-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-2-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-3-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-base-1-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-base-2-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-base-3-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-ext-2-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-pro-1-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-pro-2-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-pro-3-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-ul-1-person-ultralight-backpacking-tent",
            "naturehike-cloud-up-ul-2-person-ultralight-backpacking-tent",
        ],
        "intro": (
            "Cloud Up is a family rather than one tent. Standard, Base, Pro, UL "
            "and EXT records cover different capacities and price points, so the "
            "suffix and selected variant matter as much as the Cloud Up name."
        ),
        "takeaways": [
            "<strong>Start with capacity:</strong> compare one-, two- and three-person records separately before looking at weight.",
            "<strong>UL models:</strong> the UL 2 has the lowest representative weight among the two-person Cloud Up records in this catalog.",
            "<strong>Base models:</strong> Base records occupy the lower end of the current official reference-price range.",
            "<strong>Pro and EXT:</strong> these names identify distinct configurations, not a simple linear upgrade path.",
            "<strong>Variant warning:</strong> fabric, size and included components can change weight; verify the exact official listing before buying.",
        ],
    }
]

ACCESSORY_PATTERN = re.compile(
    r"\b(accessor(?:y|ies)|footprints?|stuff sacks?|dry bags?|pegs?|"
    r"pole sets?|pole kits?|tent poles?|inner (?:bug )?(?:tent|tarp)|shelter inner|"
    r"ground(?:sheets?| cloth)|connection|jack|pumps?|straps?|repair|"
    r"liners?|blankets?|seats?|pillows?|cots?|benches?|tables?|chairs?|"
    r"daisy chain|stakes?|tent body)\b",
    re.IGNORECASE,
)


def approved_guides(guide_type: str) -> list[dict]:
    if not GUIDE_APPROVALS_PATH.exists():
        return []
    data = json.loads(GUIDE_APPROVALS_PATH.read_text(encoding="utf-8"))
    guides = data.get("guides", []) if isinstance(data, dict) else []
    return [
        guide
        for guide in guides
        if guide.get("status") == "approved" and guide.get("type") == guide_type
    ]


def all_comparison_guides() -> list[dict]:
    return [*COMPARISON_GUIDES, *approved_guides("comparison")]


def all_collection_guides() -> list[dict]:
    return [*COLLECTION_GUIDES, *approved_guides("collection")]


def guide_page_config(
    slug: str,
    title: str,
    description: str,
    priority: str = "0.7",
    lastmod: str = DEFAULT_GUIDE_MODIFIED,
) -> dict:
    path = "/guides/" if slug == "index" else f"/guides/{slug}.html"
    file = "guides/index.html" if slug == "index" else f"guides/{slug}.html"
    return {
        "path": path,
        "file": file,
        "title": title,
        "description": description,
        "changefreq": "monthly",
        "priority": priority,
        "lastmod": lastmod,
        "schema": "generated-guide",
    }


def guide_modified(guide: dict) -> str:
    return str(guide.get("date_modified") or DEFAULT_GUIDE_MODIFIED)


def article_schema(
    site_url: str,
    path: str,
    title: str,
    description: str,
    category_label: str = "Guides",
    date_modified: str | None = None,
) -> dict:
    url = f"{site_url}{path}"
    return {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": f"{site_url}/",
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Guides",
                        "item": f"{site_url}/guides/",
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": category_label,
                        "item": url,
                    },
                ],
            },
            {
                "@type": "Article",
                "headline": title,
                "description": description,
                "url": url,
                "datePublished": PUBLISHED,
                "dateModified": date_modified or date.today().isoformat(),
                "author": {
                    "@type": "Organization",
                    "name": "CampGear Compare",
                    "url": f"{site_url}/",
                },
                "publisher": {"@id": f"{site_url}/#organization"},
                "isPartOf": {"@id": f"{site_url}/#website"},
            },
        ],
    }


def page_shell(
    *,
    title: str,
    description: str,
    canonical: str,
    schema: dict,
    current_path: str,
    body: str,
    b: ModuleType,
) -> str:
    encoded_url = quote(canonical, safe="")
    encoded_title = quote(title, safe="")
    share_tools = (
        '<aside class="static-panel guide-share" aria-label="Share this guide">'
        "<h2>Share or follow</h2>"
        '<div class="static-actions">'
        f'<a class="static-button share-link" data-share-channel="reddit" '
        f'href="https://www.reddit.com/submit?url={encoded_url}&amp;title={encoded_title}" '
        'target="_blank" rel="noopener noreferrer">Share on Reddit</a>'
        f'<a class="static-button share-link" data-share-channel="x" '
        f'href="https://twitter.com/intent/tweet?url={encoded_url}&amp;text={encoded_title}" '
        'target="_blank" rel="noopener noreferrer">Share on X</a>'
        f'<button class="static-button" type="button" data-copy-url="{b.escape_html(canonical)}">'
        "Copy link</button>"
        '<a class="static-button" href="/feed.xml">Follow via RSS</a>'
        "</div></aside>"
    )
    body_with_share = body.replace("</main>", f"{share_tools}\n</main>", 1)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        f"{b.static_page_head(title, description, canonical, schema)}\n"
        '<body data-page="guide">\n'
        f"{b.static_header(current_path)}\n"
        f"{body_with_share}\n"
        f"{b.static_footer()}\n"
        f"{GENERATED_MARKER}\n"
        "</body>\n"
        "</html>\n"
    )


def product_name(product: dict, brands: dict[str, dict], b: ModuleType) -> str:
    brand_id = product.get("brandId", "")
    return (
        f"{b.brand_display_name(brands.get(brand_id), brand_id)} "
        f"{product.get('model', '')}"
    ).strip()


def comparison_value(product: dict, key: str, b: ModuleType) -> str:
    if key == "weight":
        return b.format_weight(product) or "Not listed"
    if key == "price":
        return b.format_price(product)
    if key == "capacity":
        return b.format_capacity_display(product) or "Not listed"
    return b.spec_value(product, key) or "Not listed"


def comparison_page(
    guide: dict,
    product_map: dict[str, dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
) -> str:
    products = [product_map[pid] for pid in guide["product_ids"]]
    slug = guide["slug"]
    path = f"/guides/{slug}.html"
    canonical = f"{site_url}{path}"
    names = [product_name(p, brands, b) for p in products]
    category_path = b.category_page_path(guide["category"])
    category_name = b.category_label(guide["category"])

    spec_rows = [
        ("Weight", "weight"),
        ("Capacity", "capacity"),
        ("R-Value", "rValue"),
        ("Type / Structure", "structure"),
        ("Fabric", "fabric"),
        ("Reference Price", "price"),
    ]
    header = "".join(
        f'<th scope="col"><a href="{b.escape_html(b.product_path(p))}">'
        f"{b.escape_html(name)}</a></th>"
        for p, name in zip(products, names)
    )
    rows = []
    for label, key in spec_rows:
        values = [comparison_value(p, key, b) for p in products]
        if key not in {"weight", "price"} and all(v == "Not listed" for v in values):
            continue
        rows.append(
            f'<tr><th scope="row">{b.escape_html(label)}</th>'
            + "".join(f"<td>{b.escape_html(value)}</td>" for value in values)
            + "</tr>"
        )

    source_links = " · ".join(
        f'<a href="{b.escape_html(p.get("sourceUrl", ""))}" '
        f'rel="noopener noreferrer" target="_blank">{b.escape_html(name)} official listing</a>'
        for p, name in zip(products, names)
        if p.get("sourceUrl")
    )
    takeaways = "".join(f"<li>{item}</li>" for item in guide["takeaways"])
    verdict = ""
    if guide.get("verdict"):
        verdict = (
            '    <section class="static-panel" aria-labelledby="bottom-line">\n'
            '      <h2 id="bottom-line">Bottom line</h2>\n'
            f'      <p>{b.escape_html(guide["verdict"])}</p>\n'
            "    </section>\n"
        )
    reviewed_note = ""
    if guide.get("reviewed_on"):
        reviewed_on = b.escape_html(guide["reviewed_on"])
        reviewed_note = (
            '      <p class="page__lead page__lead--compact">'
            f'Data manually reviewed <time datetime="{reviewed_on}">{reviewed_on}</time>.'
            "</p>\n"
        )
    limitations = guide.get(
        "limitations",
        "This is a specification comparison, not a hands-on review. Weights and "
        "prices can vary by size, fabric, season and market. We use representative "
        "values from brand listings and link the source so you can verify the exact "
        "variant before buying.",
    )
    product_links = "".join(
        f'<li><a href="{b.escape_html(b.product_path(p))}">'
        f"{b.escape_html(name)} — full specs</a></li>"
        for p, name in zip(products, names)
    )
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        f"    <span>{b.escape_html(guide['title'])}</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        f'      <p class="page__eyebrow">{b.escape_html(guide["eyebrow"])}</p>\n'
        f'      <h1 class="page__title">{b.escape_html(guide["title"].split(" — ")[0])}</h1>\n'
        f'      <p class="page__lead">{b.escape_html(guide["intro"])}</p>\n'
        '      <div class="static-actions">\n'
        f'        <a class="static-button static-button--primary" href="{b.escape_html(category_path)}">'
        f"Open full {b.escape_html(category_name.lower())} table</a>\n"
        "      </div>\n"
        "    </header>\n"
        f"{verdict}"
        '    <section class="static-panel" aria-labelledby="spec-table">\n'
        '      <h2 id="spec-table">Official specs side by side</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        f'        <thead><tr><th scope="col">Spec</th>{header}</tr></thead>\n'
        f"        <tbody>{''.join(rows)}</tbody>\n"
        "      </table></div>\n"
        f'      <p class="page__lead page__lead--compact">Sources: {source_links}</p>\n'
        f"{reviewed_note}"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="takeaways">\n'
        '      <h2 id="takeaways">Evidence and decision points</h2>\n'
        f'      <ul class="static-link-list">{takeaways}</ul>\n'
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Method and limitations</h2>\n'
        f"      <p>{b.escape_html(limitations)}</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="related-products">\n'
        '      <h2 id="related-products">Full product pages</h2>\n'
        f'      <ul class="static-link-list">{product_links}</ul>\n'
        f'      <p><a href="/guides/">Browse all data-backed guides</a> · '
        f'<a href="{b.escape_html(category_path)}">Compare all {b.escape_html(category_name.lower())}</a></p>\n'
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    schema = article_schema(
        site_url,
        path,
        guide["title"],
        guide["description"],
        guide["eyebrow"],
        guide_modified(guide),
    )
    return page_shell(
        title=guide["title"],
        description=guide["description"],
        canonical=canonical,
        schema=schema,
        current_path="/guides/",
        body=body,
        b=b,
    )


def collection_page(
    guide: dict,
    product_map: dict[str, dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
) -> str:
    products = [product_map[pid] for pid in guide["product_ids"]]
    if not guide.get("preserve_product_order"):
        products.sort(
            key=lambda p: (
                b.format_capacity_display(p) or "99-person",
                b.parse_weight_kg(p) or 99,
                p.get("model", ""),
            )
        )
    slug = guide["slug"]
    path = f"/guides/{slug}.html"
    category_path = b.category_page_path(guide["category"])
    category_name = b.category_label(guide["category"])
    columns = guide.get("columns") or [
        {"label": "Capacity", "key": "capacity"},
        {"label": "Weight", "key": "weight"},
        {"label": "Structure", "key": "structure"},
        {"label": "Reference Price", "key": "price"},
    ]
    rows = []
    for product in products:
        cells = "".join(
            f"<td>{b.escape_html(comparison_value(product, column['key'], b))}</td>"
            for column in columns
        )
        rows.append(
            "<tr>"
            f'<td><a href="{b.escape_html(b.product_path(product))}">'
            f"{b.escape_html(product.get('model', ''))}</a></td>"
            f"{cells}"
            "</tr>"
        )
    column_headers = "".join(
        f'<th scope="col">{b.escape_html(column["label"])}</th>'
        for column in columns
    )
    takeaways = "".join(f"<li>{item}</li>" for item in guide["takeaways"])
    source_links = "".join(
        f'<li><a href="{b.escape_html(product.get("sourceUrl", ""))}" '
        f'rel="noopener noreferrer" target="_blank">'
        f'{b.escape_html(product_name(product, brands, b))} official listing</a></li>'
        for product in products
        if product.get("sourceUrl")
    )
    verdict = ""
    if guide.get("verdict"):
        verdict = (
            '    <section class="static-panel" aria-labelledby="bottom-line">\n'
            '      <h2 id="bottom-line">Bottom line</h2>\n'
            f'      <p>{b.escape_html(guide["verdict"])}</p>\n'
            "    </section>\n"
        )
    reviewed_note = ""
    if guide.get("reviewed_on"):
        reviewed_on = b.escape_html(guide["reviewed_on"])
        reviewer = ""
        if guide.get("reviewer"):
            reviewer = (
                'Reviewed by <a href="/about.html">'
                f'{b.escape_html(guide["reviewer"])}</a>. '
            )
        reviewed_note = (
            '      <p class="page__lead page__lead--compact">'
            f'{reviewer}Data and official prices manually reviewed '
            f'<time datetime="{reviewed_on}">{reviewed_on}</time>.'
            "</p>\n"
        )
    limitations = guide.get(
        "limitations",
        "This is a specification guide, not a hands-on review. Values come from "
        "the current official-source catalog and may describe a representative "
        "size or variant.",
    )
    brand_link = ""
    if guide.get("brand_id"):
        brand_id = guide["brand_id"]
        brand_name = b.brand_display_name(brands.get(brand_id), brand_id)
        brand_link = (
            f'<a href="{b.escape_html(b.brand_home_path(brand_id))}">'
            f'{b.escape_html(brand_name)} gear hub</a> · '
        )
    related_section = ""
    if guide.get("related_guides"):
        related_items = "".join(
            f'<li><a href="/guides/{b.escape_html(item["slug"])}.html">'
            f'{b.escape_html(item["label"])}</a></li>'
            for item in guide["related_guides"]
        )
        related_section = (
            '    <section class="static-panel" aria-labelledby="related-guides">\n'
            '      <h2 id="related-guides">Related buying guides</h2>\n'
            f'      <ul class="static-link-list">{related_items}</ul>\n'
            "    </section>\n"
        )
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        f"    <span>{b.escape_html(guide['title'])}</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        f'      <p class="page__eyebrow">{b.escape_html(guide["eyebrow"])}</p>\n'
        f'      <h1 class="page__title">{b.escape_html(guide["title"].split(" — ")[0])}</h1>\n'
        f'      <p class="page__lead">{b.escape_html(guide["intro"])}</p>\n'
        "    </header>\n"
        f"{verdict}"
        '    <section class="static-panel" aria-labelledby="models">\n'
        f'      <h2 id="models">{len(products)} models side by side</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        f'        <thead><tr><th scope="col">Model</th>{column_headers}</tr></thead>\n'
        f"        <tbody>{''.join(rows)}</tbody>\n"
        "      </table></div>\n"
        f"{reviewed_note}"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="takeaways">\n'
        '      <h2 id="takeaways">How to narrow the range</h2>\n'
        f'      <ul class="static-link-list">{takeaways}</ul>\n'
        "    </section>\n"
        f"{related_section}"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Method and limitations</h2>\n'
        f"      <p>{b.escape_html(limitations)}</p>\n"
        '      <h3>Official product sources</h3>\n'
        f'      <ul class="static-link-list">{source_links}</ul>\n'
        f'      <p>{brand_link}<a href="{b.escape_html(category_path)}">Compare all '
        f"{b.escape_html(category_name.lower())}</a> · "
        '<a href="/guides/">Browse all data-backed guides</a></p>\n'
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    return page_shell(
        title=guide["title"],
        description=guide["description"],
        canonical=f"{site_url}{path}",
        schema=article_schema(
            site_url,
            path,
            guide["title"],
            guide["description"],
            guide["eyebrow"],
            guide_modified(guide),
        ),
        current_path="/guides/",
        body=body,
        b=b,
    )


def lightweight_tents_page(
    product_map: dict[str, dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
    seo_override: dict | None = None,
) -> tuple[dict, str]:
    slug = "2-person-backpacking-tents-under-2kg"
    override = seo_override or {}
    title = override.get("title") or (
        "2-Person Backpacking Tents Under 2 kg — 14 Models Compared"
    )
    description = override.get("description") or (
        "Compare 14 two-person backpacking tents under 2 kg by listed weight, "
        "structure and official reference price."
    )
    page = guide_page_config(
        slug, title, description, lastmod=LIGHTWEIGHT_TENTS_REVIEWED
    )
    products = [product_map[pid] for pid in LIGHTWEIGHT_TENT_IDS]
    products.sort(key=lambda p: (b.parse_weight_kg(p) or 99, b.parse_price(p) or 99999))
    rows = []
    for product in products:
        brand_id = product.get("brandId", "")
        brand = b.brand_display_name(brands.get(brand_id), brand_id)
        rows.append(
            "<tr>"
            f"<td>{b.escape_html(brand)}</td>"
            f'<td><a href="{b.escape_html(b.product_path(product))}">'
            f"{b.escape_html(product.get('model', ''))}</a></td>"
            f"<td>{b.escape_html(b.format_weight(product) or 'Not listed')}</td>"
            f"<td>{b.escape_html(b.spec_value(product, 'structure') or 'Not listed')}</td>"
            f"<td>{b.escape_html(b.format_price(product))}</td>"
            "</tr>"
        )
    path = page["path"]
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        "    <span>2-person tents under 2 kg</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        '      <p class="page__eyebrow">Weight-filtered tent shortlist</p>\n'
        '      <h1 class="page__title">2-Person Backpacking Tents Under 2 kg</h1>\n'
        "      <p class=\"page__lead\">A curated shortlist of complete two-person "
        "shelters whose representative listed weight is no more than 2 kg. "
        "Accessories, inner tents and records with conflicting capacities were "
        "removed manually.</p>\n"
        "    </header>\n"
        '    <section class="static-panel" aria-labelledby="shortlist">\n'
        '      <h2 id="shortlist">14 models, lightest first</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        "        <thead><tr><th>Brand</th><th>Model</th><th>Weight</th>"
        "<th>Structure</th><th>Price</th></tr></thead>\n"
        f"        <tbody>{''.join(rows)}</tbody>\n"
        "      </table></div>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="how-to-read">\n'
        '      <h2 id="how-to-read">How to use this shortlist</h2>\n'
        "      <ul class=\"static-link-list\">"
        "<li><strong>Check the weight basis:</strong> trail, minimum and packaged weights are not always equivalent.</li>"
        "<li><strong>Check the variant:</strong> fabric and inner-tent choices can change total weight.</li>"
        "<li><strong>Check support requirements:</strong> trekking-pole shelters may exclude the poles from listed weight.</li>"
        "<li><strong>Use price as a reference:</strong> currencies, promotions and stock change over time.</li>"
        "<li><strong>Do not use this as a car-camping shortlist:</strong> the 2 kg filter rewards low carried weight, but it does not compare floor area, peak height, mesh coverage or the number of doors and vents that matter more for roomy summer car camping.</li>"
        "</ul>\n"
        "      <p><strong>Review note:</strong> Scope and ventilation limitations were reviewed on August 5, 2026 after a reader question about choosing a larger summer car-camping tent.</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Methodology</h2>\n'
        "      <p>We filtered the CampGear Compare official-source catalog for "
        "two-person tents with a positive representative weight at or below "
        "2.0 kg, then manually removed accessories and records whose model name "
        "conflicted with the capacity field. This is a spec shortlist, not a "
        "hands-on ranking.</p>\n"
        '      <p><a href="/tent.html">Compare all tents</a> · '
        '<a href="/guides/">Browse all guides</a></p>\n'
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    html = page_shell(
        title=title,
        description=description,
        canonical=f"{site_url}{path}",
        schema=article_schema(
            site_url,
            path,
            title,
            description,
            "Lightweight tents",
            LIGHTWEIGHT_TENTS_REVIEWED,
        ),
        current_path="/guides/",
        body=body,
        b=b,
    )
    return page, html


def guide_links_by_product() -> dict[str, list[tuple[str, str]]]:
    links: dict[str, list[tuple[str, str]]] = {}
    for guide in [*all_comparison_guides(), *all_collection_guides()]:
        path = f"/guides/{guide['slug']}.html"
        label = guide["title"].split(" — ")[0]
        for product_id in guide["product_ids"]:
            links.setdefault(product_id, []).append((path, label))
    lightweight_path = "/guides/2-person-backpacking-tents-under-2kg.html"
    for product_id in LIGHTWEIGHT_TENT_IDS:
        links.setdefault(product_id, []).append(
            (lightweight_path, "2-Person Backpacking Tents Under 2 kg")
        )
    return links


def guide_links_by_brand() -> dict[str, list[tuple[str, str]]]:
    links: dict[str, list[tuple[str, str]]] = {}
    for guide in [*all_comparison_guides(), *all_collection_guides()]:
        brand_id = guide.get("brand_id")
        if not brand_id:
            continue
        path = f"/guides/{guide['slug']}.html"
        label = guide["title"].split(" — ")[0]
        links.setdefault(brand_id, []).append((path, label))
    return links


def clean_report_rows(products: list[dict], category: str, b: ModuleType) -> list[dict]:
    rows = []
    for product in products:
        if product.get("category") != category:
            continue
        if product.get("inSummaryTable") is False:
            continue
        if ACCESSORY_PATTERN.search(product.get("model", "")):
            continue
        source_terms = re.sub(r"[-_/]+", " ", product.get("sourceUrl", ""))
        if re.search(
            r"\b(inner (?:bug )?(?:tent|tarp)|ground cloth|shelter inner|"
            r"accessory vestibule|daisy chain)\b",
            source_terms,
            re.IGNORECASE,
        ):
            continue
        weight = b.parse_weight_kg(product)
        price = b.parse_price(product)
        if weight is None or weight <= 0 or price is None or price <= 0:
            continue
        rows.append(product)
    return rows


def data_report_page(
    products: list[dict],
    brands: dict[str, dict],
    site_url: str,
    b: ModuleType,
) -> tuple[dict, str]:
    slug = "camping-gear-weight-price-report-2026"
    categories = ["tent", "tarp", "sleeping-bag", "sleeping-pad", "stove"]
    stats = []
    report_rows: list[dict] = []
    total = 0
    for category in categories:
        rows = clean_report_rows(products, category, b)
        report_rows.extend(rows)
        total += len(rows)
        weights = sorted(b.parse_weight_kg(p) for p in rows)
        usd_prices = sorted(
            b.parse_price(p)
            for p in rows
            if str(p.get("currency") or "USD").upper() == "USD"
        )
        stats.append(
            {
                "category": category,
                "count": len(rows),
                "brands": len({p.get("brandId") for p in rows}),
                "median_weight": statistics.median(weights),
                "usd_price_count": len(usd_prices),
                "median_usd_price": statistics.median(usd_prices),
                "under_1kg": sum(weight <= 1 for weight in weights),
                "under_200_usd": sum(price <= 200 for price in usd_prices),
            }
        )
    title = f"Camping Gear Weight & Price Report 2026 — {total} Products"
    description = (
        f"Original analysis of {total} tents, tarps, sleeping bags, pads and "
        "stoves: median weight, price and lightweight product counts."
    )
    page = guide_page_config(
        slug, title, description, "0.8", WEIGHT_PRICE_REPORT_REVIEWED
    )
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / "camping-gear-weight-price-2026.csv"
    with report_path.open("w", encoding="utf-8", newline="") as csv_file:
        writer = csv.writer(csv_file, lineterminator="\n")
        writer.writerow(
            [
                "category",
                "brand",
                "model",
                "weight_kg",
                "reference_price",
                "currency",
                "data_reviewed",
                "product_url",
                "official_source",
            ]
        )
        for product in sorted(
            report_rows,
            key=lambda p: (
                p.get("category", ""),
                p.get("brandId", ""),
                p.get("model", ""),
            ),
        ):
            brand_id = product.get("brandId", "")
            writer.writerow(
                [
                    product.get("category", ""),
                    b.brand_display_name(brands.get(brand_id), brand_id),
                    product.get("model", ""),
                    b.parse_weight_kg(product),
                    b.parse_price(product),
                    product.get("currency", "USD"),
                    WEIGHT_PRICE_REPORT_REVIEWED,
                    f"{site_url}{b.product_path(product)}",
                    product.get("sourceUrl", ""),
                ]
            )
    rows_html = "".join(
        "<tr>"
        f"<td>{b.escape_html(b.category_label(row['category']))}</td>"
        f"<td>{row['count']}</td>"
        f"<td>{row['brands']}</td>"
        f"<td>{row['median_weight']:.2f} kg</td>"
        f"<td>{row['usd_price_count']}</td>"
        f"<td>${row['median_usd_price']:.2f}</td>"
        f"<td>{row['under_1kg']}</td>"
        f"<td>{row['under_200_usd']}</td>"
        "</tr>"
        for row in stats
    )
    tent_lightweight_share = stats[0]["under_1kg"] / stats[0]["count"] * 100
    bag_lightweight_share = stats[2]["under_1kg"] / stats[2]["count"] * 100
    pad_lightweight_share = stats[3]["under_1kg"] / stats[3]["count"] * 100
    tent_budget_share = stats[0]["under_200_usd"] / stats[0]["usd_price_count"] * 100
    pad_budget_share = stats[3]["under_200_usd"] / stats[3]["usd_price_count"] * 100
    path = page["path"]
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>\n'
        '    <a href="/guides/">Guides</a><span aria-hidden="true">/</span>\n'
        "    <span>2026 weight and price report</span>\n"
        "  </nav>\n"
        '  <article class="static-detail">\n'
        '    <header class="page__head">\n'
        '      <p class="page__eyebrow">Original catalog analysis · August 2026</p>\n'
        '      <h1 class="page__title">Camping Gear Weight &amp; Price Report 2026</h1>\n'
        f'      <p class="page__lead">We analyzed {total} product records with '
        "usable weight and price data across five camping categories. The result "
        "is a transparent benchmark for comparing a product with its category.</p>\n"
        '      <div class="static-actions"><a class="static-button static-button--primary" '
        'href="/data/reports/camping-gear-weight-price-2026.csv" download>'
        "Download the cleaned CSV</a></div>\n"
        "    </header>\n"
        '    <section class="static-panel" aria-labelledby="results">\n'
        '      <h2 id="results">Category benchmarks</h2>\n'
        '      <div class="table-wrap"><table class="compare-table static-table">\n'
        "        <thead><tr><th>Category</th><th>Products</th><th>Brands</th>"
        "<th>Median Weight</th><th>USD-priced</th><th>Median USD Price</th>"
        "<th>≤ 1 kg</th><th>≤ $200 USD</th></tr></thead>\n"
        f"        <tbody>{rows_html}</tbody>\n"
        "      </table></div>\n"
        "      <p class=\"page__lead page__lead--compact\">Price medians and "
        "the ≤ $200 counts use USD records only. Other currencies remain in the "
        "downloadable CSV but are excluded from price benchmarks; no exchange-rate "
        "conversion is applied.</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="findings">\n'
        '      <h2 id="findings">What the data shows</h2>\n'
        "      <ul class=\"static-link-list\">"
        f"<li><strong>Tents:</strong> {stats[0]['count']} clean records have a median representative weight of {stats[0]['median_weight']:.2f} kg.</li>"
        f"<li><strong>Sleeping bags:</strong> {stats[2]['under_1kg']} of {stats[2]['count']} records weigh 1 kg or less.</li>"
        f"<li><strong>Sleeping pads:</strong> {stats[3]['under_200_usd']} of {stats[3]['usd_price_count']} USD-priced records list a reference price at or below $200.</li>"
        f"<li><strong>Stoves:</strong> the median representative weight is {stats[4]['median_weight']:.2f} kg in the cleaned sample.</li>"
        "</ul>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="citable-findings">\n'
        '      <h2 id="citable-findings">Three cross-category findings</h2>\n'
        '      <ul class="static-link-list">'
        f"<li><strong>Sub-1 kg products are category-dependent:</strong> {pad_lightweight_share:.1f}% of sleeping pads and {bag_lightweight_share:.1f}% of sleeping bags in the cleaned sample are 1 kg or less, compared with {tent_lightweight_share:.1f}% of tents.</li>"
        f"<li><strong>The $200 line separates pads and tents:</strong> {pad_budget_share:.1f}% of USD-priced sleeping pads are listed at $200 or less, versus {tent_budget_share:.1f}% of USD-priced tents.</li>"
        f"<li><strong>Tarps are not automatically lighter in this catalog:</strong> the tarp median is {stats[1]['median_weight']:.2f} kg versus {stats[0]['median_weight']:.2f} kg for tents because the tarp sample includes large shelter systems as well as backpacking tarps.</li>"
        "</ul>\n"
        '      <p class="page__lead page__lead--compact">These are descriptive catalog results, not market-share estimates. Product mix differs by category, and price percentages use USD records only.</p>\n'
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="methodology">\n'
        '      <h2 id="methodology">Reproducible methodology</h2>\n'
        "      <p>Source data comes from brand product pages in the public "
        "CampGear Compare catalog. We included visible records with positive "
        "weight and price values, then excluded model names that clearly describe "
        "accessories such as footprints, stuff sacks, pumps, repair parts and "
        "inner tents. Weight medians use every included row; price medians and "
        "price thresholds use USD rows only. Records in other currencies stay in "
        "the CSV for inspection and are never compared numerically without currency "
        "conversion. The report is regenerated by <code>scripts/build_guides.py</code>.</p>\n"
        "      <p>Download or inspect the source records through the site's "
        '<a href="/about.html">methodology page</a>, use the '
        '<a href="/data/reports/camping-gear-weight-price-2026.csv" download>cleaned CSV</a>, '
        "and verify individual values "
        "using the official source link on every product page.</p>\n"
        "    </section>\n"
        '    <section class="static-panel" aria-labelledby="explore">\n'
        '      <h2 id="explore">Explore the underlying catalog</h2>\n'
        '      <ul class="static-link-list">'
        '<li><a href="/tent.html">Tent comparison table</a></li>'
        '<li><a href="/sleeping-bag.html">Sleeping bag comparison table</a></li>'
        '<li><a href="/sleeping-pad.html">Sleeping pad comparison table</a></li>'
        '<li><a href="/tarp.html">Tarp comparison table</a></li>'
        '<li><a href="/stove.html">Stove comparison table</a></li>'
        "</ul>\n"
        "    </section>\n"
        "  </article>\n"
        "</main>"
    )
    schema = article_schema(
        site_url,
        path,
        title,
        description,
        "Data report",
        WEIGHT_PRICE_REPORT_REVIEWED,
    )
    schema["@graph"].append(
        {
            "@type": "Dataset",
            "name": "CampGear Compare Weight and Price Dataset 2026",
            "description": description,
            "url": f"{site_url}{path}",
            "datePublished": PUBLISHED,
            "dateModified": WEIGHT_PRICE_REPORT_REVIEWED,
            "creator": {
                "@type": "Organization",
                "name": "CampGear Compare",
                "url": f"{site_url}/",
            },
            "variableMeasured": [
                "Product category",
                "Brand",
                "Representative weight in kilograms",
                "Reference price",
                "Currency",
            ],
            "distribution": {
                "@type": "DataDownload",
                "encodingFormat": "text/csv",
                "contentUrl": (
                    f"{site_url}/data/reports/"
                    "camping-gear-weight-price-2026.csv"
                ),
            },
        }
    )
    html = page_shell(
        title=title,
        description=description,
        canonical=f"{site_url}{path}",
        schema=schema,
        current_path="/guides/",
        body=body,
        b=b,
    )
    return page, html


def guides_index_page(
    pages: list[dict],
    site_url: str,
    b: ModuleType,
) -> tuple[dict, str]:
    title = "Camping Gear Guides & Data Reports | CampGear Compare"
    description = (
        "Data-backed camping gear comparisons, lightweight shortlists and "
        "original weight and price reports using official product specs."
    )
    page = guide_page_config("index", title, description, "0.8", WEIGHT_PRICE_REPORT_REVIEWED)
    links = "".join(
        '<section class="static-panel">'
        f'<h2><a href="{b.escape_html(item["path"])}">{b.escape_html(item["title"])}</a></h2>'
        f'<p>{b.escape_html(item["description"])}</p>'
        "</section>"
        for item in pages
    )
    analytics_path = ROOT / "data" / "analytics.json"
    analytics = (
        json.loads(analytics_path.read_text(encoding="utf-8"))
        if analytics_path.exists()
        else {}
    )
    contact_email = analytics.get("contactEmail", "")
    email_link = (
        f'<a class="static-button" href="mailto:{b.escape_html(contact_email)}'
        '?subject=Subscribe%20to%20CampGear%20Compare%20weekly%20digest">'
        "Join the email digest</a>"
        if contact_email
        else ""
    )
    body = (
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a><span aria-hidden="true">/</span>'
        "    <span>Guides</span>\n"
        "  </nav>\n"
        '  <header class="page__head">\n'
        '    <p class="page__eyebrow">Official specs, explained</p>\n'
        '    <h1 class="page__title">Camping Gear Guides &amp; Data Reports</h1>\n'
        "    <p class=\"page__lead\">Focused comparisons and original catalog "
        "analysis. These pages organize official specifications; they do not "
        "claim hands-on testing.</p>\n"
        "  </header>\n"
        '  <section class="static-panel" aria-labelledby="follow-guides">\n'
        '    <h2 id="follow-guides">Get new comparisons</h2>\n'
        "    <p>Follow the RSS feed for every new guide, or email us to join the "
        "free weekly digest. Email requests are handled manually and can be "
        "cancelled at any time.</p>\n"
        '    <div class="static-actions">'
        '<a class="static-button static-button--primary" href="/feed.xml">Follow via RSS</a>'
        f"{email_link}</div>\n"
        "  </section>\n"
        f"{links}\n"
        "</main>"
    )
    schema = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": title,
        "description": description,
        "url": f"{site_url}/guides/",
        "mainEntity": {
            "@type": "ItemList",
            "numberOfItems": len(pages),
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": index,
                    "name": item["title"],
                    "url": f"{site_url}{item['path']}",
                }
                for index, item in enumerate(pages, start=1)
            ],
        },
    }
    html = page_shell(
        title=title,
        description=description,
        canonical=f"{site_url}/guides/",
        schema=schema,
        current_path="/guides/",
        body=body,
        b=b,
    )
    return page, html


def write_rss_feed(pages: list[dict], site_url: str, b: ModuleType) -> None:
    items = []
    for page in pages:
        url = f"{site_url}{page['path']}"
        published = date.fromisoformat(str(page.get("lastmod", PUBLISHED))[:10])
        items.append(
            "    <item>\n"
            f"      <title>{b.escape_html(page['title'])}</title>\n"
            f"      <link>{b.escape_html(url)}</link>\n"
            f"      <guid isPermaLink=\"true\">{b.escape_html(url)}</guid>\n"
            f"      <description>{b.escape_html(page['description'])}</description>\n"
            f"      <pubDate>{published.strftime('%a, %d %b %Y 00:00:00 +0000')}</pubDate>\n"
            "    </item>"
        )
    feed = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0">\n'
        "  <channel>\n"
        "    <title>CampGear Compare Guides</title>\n"
        f"    <link>{site_url}/guides/</link>\n"
        "    <description>New data-backed camping gear comparisons and reports.</description>\n"
        "    <language>en-us</language>\n"
        f"{chr(10).join(items)}\n"
        "  </channel>\n"
        "</rss>\n"
    )
    (ROOT / "feed.xml").write_text(feed, encoding="utf-8")


def build_guides(
    site_url: str,
    products: list[dict],
    brands: dict[str, dict],
    b: ModuleType,
    seo_overrides: dict | None = None,
) -> list[dict]:
    GUIDE_DIR.mkdir(exist_ok=True)
    product_map = {product.get("id"): product for product in products}
    pages: list[dict] = []
    page_overrides = (seo_overrides or {}).get("pages") or {}

    for guide in all_comparison_guides():
        missing = [pid for pid in guide["product_ids"] if pid not in product_map]
        if missing:
            raise ValueError(f"{guide['slug']}: missing product IDs: {missing}")
        page = guide_page_config(
            guide["slug"],
            guide["title"],
            guide["description"],
            lastmod=guide_modified(guide),
        )
        (GUIDE_DIR / f"{guide['slug']}.html").write_text(
            comparison_page(guide, product_map, brands, site_url, b),
            encoding="utf-8",
        )
        pages.append(page)

    for guide in all_collection_guides():
        missing = [pid for pid in guide["product_ids"] if pid not in product_map]
        if missing:
            raise ValueError(f"{guide['slug']}: missing product IDs: {missing}")
        page = guide_page_config(
            guide["slug"],
            guide["title"],
            guide["description"],
            lastmod=guide_modified(guide),
        )
        (GUIDE_DIR / f"{guide['slug']}.html").write_text(
            collection_page(guide, product_map, brands, site_url, b),
            encoding="utf-8",
        )
        pages.append(page)

    missing_tents = [pid for pid in LIGHTWEIGHT_TENT_IDS if pid not in product_map]
    if missing_tents:
        raise ValueError(f"lightweight tent guide: missing product IDs: {missing_tents}")
    lightweight_path = "/guides/2-person-backpacking-tents-under-2kg.html"
    page, html = lightweight_tents_page(
        product_map,
        brands,
        site_url,
        b,
        page_overrides.get(lightweight_path),
    )
    (GUIDE_DIR / "2-person-backpacking-tents-under-2kg.html").write_text(
        html, encoding="utf-8"
    )
    pages.append(page)

    page, html = data_report_page(products, brands, site_url, b)
    (GUIDE_DIR / "camping-gear-weight-price-report-2026.html").write_text(
        html, encoding="utf-8"
    )
    pages.append(page)

    existing_page = guide_page_config(
        "snow-peak-amenity-dome-2-vs-naturehike-cloud-up-2",
        "Snow Peak Amenity Dome 2 vs Naturehike Cloud Up 2",
        "A 2-person car-camping tent compared with a lighter budget backpacking tent.",
    )
    index_page, index_html = guides_index_page(
        [existing_page, *pages], site_url, b
    )
    (GUIDE_DIR / "index.html").write_text(index_html, encoding="utf-8")
    write_rss_feed([existing_page, *pages], site_url, b)
    return [index_page, *pages]


def main() -> int:
    import build_sitemap as b

    seo = b.load_json(b.SEO_PATH)
    site_url = seo["siteUrl"].rstrip("/")
    brands_data = b.load_json(b.DATA / "brands.json")
    brands = b.brand_map(brands_data if isinstance(brands_data, list) else [])
    products = b.load_official_products()
    pages = build_guides(site_url, products, brands, b, b.load_seo_overrides())
    print(f"Generated {len(pages)} guide page(s) in {GUIDE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
