#!/usr/bin/env python3
"""Generate robots.txt, sitemap.xml, and inject SEO meta / JSON-LD into HTML."""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
SEO_PATH = DATA / "seo.json"
SEO_HEAD_START = "<!-- @seo-head -->"
SEO_HEAD_END = "<!-- @seo-head:end -->"
SEO_CRAWL_START = "<!-- @seo-crawl -->"
SEO_CRAWL_END = "<!-- @seo-crawl:end -->"
ITEM_LIST_LIMIT = 30
GENERATED_MARKER = "<!-- Generated by scripts/build_sitemap.py; do not edit directly. -->"
PRODUCT_DIR = ROOT / "products"
BRAND_DIR = ROOT / "brands"
MIN_BRAND_CATEGORY_PRODUCTS = 3

CATEGORY_LABELS = {
    "tent": "Tents",
    "tarp": "Tarps",
    "sleeping-bag": "Sleeping Bags",
    "sleeping-pad": "Sleeping Pads",
    "stove": "Stoves",
    "backpack": "Backpacks",
    "table": "Camp Tables",
    "chair": "Camp Chairs",
    "other": "Camping Gear",
}

CATEGORY_PAGE_PATHS = {
    "tent": "/tent.html",
    "tarp": "/tarp.html",
    "sleeping-bag": "/sleeping-bag.html",
    "sleeping-pad": "/sleeping-pad.html",
    "stove": "/stove.html",
    "backpack": "/backpack.html",
    "table": "/furniture.html",
    "chair": "/furniture.html",
    "other": "/etc.html",
}


def load_json(path: Path) -> dict | list:
    return json.loads(path.read_text(encoding="utf-8"))


def load_official_products() -> list[dict]:
    sys.path.insert(0, str(ROOT / "scripts" / "scrape"))
    from common import is_visible_on_site  # noqa: E402

    products: list[dict] = []
    official = DATA / "official"
    index_path = official / "index.json"
    if index_path.exists():
        brand_ids = load_json(index_path).get("brandIds", [])
    else:
        brand_ids = [
            p.name
            for p in official.iterdir()
            if p.is_dir() and (p / "products.json").exists()
        ]

    for brand_id in brand_ids:
        path = official / brand_id / "products.json"
        if not path.exists():
            continue
        batch = load_json(path)
        if isinstance(batch, list):
            products.extend(
                p for p in batch if isinstance(p, dict) and is_visible_on_site(p)
            )
    return products


def brand_map(brands: list[dict]) -> dict[str, dict]:
    return {b["id"]: b for b in brands if b.get("id")}


def brand_display_name(brand: dict | None, brand_id: str) -> str:
    if not brand:
        return brand_id
    return brand.get("nameEn") or brand.get("name") or brand_id


def brand_rank(brand: dict | None) -> int:
    if not brand:
        return 9999
    rank = brand.get("rank")
    return int(rank) if isinstance(rank, (int, float)) else 9999


def category_label(category: str | None) -> str:
    return CATEGORY_LABELS.get(category or "", "Camping Gear")


def category_page_path(category: str | None) -> str:
    return CATEGORY_PAGE_PATHS.get(category or "", "/")


def product_path(product: dict) -> str:
    return f"/products/{product.get('id', '')}.html"


def brand_category_path(brand_id: str, category: str) -> str:
    return f"/brands/{brand_id}-{category}.html"


def product_url(site_url: str, product: dict) -> str:
    return f"{site_url}{product_path(product)}"


def brand_category_url(site_url: str, brand_id: str, category: str) -> str:
    return f"{site_url}{brand_category_path(brand_id, category)}"


def source_lastmod_for_product(product: dict) -> str:
    brand_id = product.get("brandId")
    if brand_id:
        catalog_path = DATA / "official" / brand_id / "products.json"
        if catalog_path.exists():
            return date.fromtimestamp(catalog_path.stat().st_mtime).isoformat()
    return date.today().isoformat()


def first_value(*values: object) -> str:
    for value in values:
        if value is not None and value != "":
            return str(value)
    return ""


def spec_value(product: dict, key: str) -> str:
    specs = product.get("specs") or {}
    return first_value(product.get(key), specs.get(key))


def format_price(product: dict) -> str:
    currency = product.get("currency") or "USD"
    price_min = product.get("priceMin", product.get("price"))
    price_max = product.get("priceMax", product.get("price"))
    if price_min is None and price_max is None:
        return "Price not listed"
    suffix = f" {currency}"
    if price_min is not None and price_max is not None and price_min != price_max:
        return f"{price_min:g}–{price_max:g}{suffix}"
    price = price_min if price_min is not None else price_max
    return f"{price:g}{suffix}" if isinstance(price, (int, float)) else f"{price}{suffix}"


def format_weight(product: dict) -> str:
    weight_display = spec_value(product, "weightDisplay") or spec_value(product, "weightRange")
    if weight_display:
        return weight_display
    weight_kg = spec_value(product, "weightKg")
    return f"~{weight_kg} kg" if weight_kg else ""


def format_capacity_display(product: dict) -> str:
    raw = spec_value(product, "capacity")
    if raw:
        text = str(raw).strip()
        text = re.sub(r"-tent$", "", text, flags=re.IGNORECASE)
        text = re.sub(r"\bppl\b", "person", text, flags=re.IGNORECASE)
        person_match = re.search(r"(\d+)\s*[-–]\s*(\d+)\s*人", text)
        if person_match:
            return f"{person_match.group(2)}-person"
        single_match = re.search(r"(\d+)\s*人", text)
        if single_match:
            return f"{single_match.group(1)}-person"
        person_range = re.search(r"(\d+)\s*[-–]\s*(\d+)\s*person", text, flags=re.IGNORECASE)
        if person_range:
            return f"{person_range.group(2)}-person"
        single_person = re.search(r"(\d+)\s*person", text, flags=re.IGNORECASE)
        if single_person:
            return f"{single_person.group(1)}-person"
        return text
    model = str(product.get("model") or "")
    for pattern in (
        r"(?:dome|cabin|shelter|tent)\s+(\d+)",
        r"\b(\d+)\s*person",
        r"#(\d+)\b",
    ):
        match = re.search(pattern, model, flags=re.IGNORECASE)
        if match:
            return f"{match.group(1)}-person"
    return ""


def category_count_label(category: str) -> str:
    labels = {
        "tent": "tents",
        "tarp": "tarps",
        "sleeping-bag": "sleeping bags",
        "sleeping-pad": "sleeping pads",
        "stove": "stoves",
        "backpack": "backpacks",
        "table": "tables",
        "chair": "chairs",
    }
    return labels.get(category, category_label(category).lower())


def product_page_title(product: dict, brands: dict[str, dict]) -> str:
    brand_id = product.get("brandId", "")
    brand = brand_display_name(brands.get(brand_id), brand_id)
    model = product.get("model", "")
    return f"{brand} {model} — Weight, Specs & Price".strip()


def product_meta_description(product: dict, brands: dict[str, dict]) -> str:
    brand_id = product.get("brandId", "")
    brand = brand_display_name(brands.get(brand_id), brand_id)
    model = product.get("model", "")
    category = product.get("category", "")
    facts = []
    weight = format_weight(product)
    if weight:
        facts.append(weight)
    capacity = format_capacity_display(product)
    if capacity:
        facts.append(capacity)
    r_value = spec_value(product, "rValue")
    if r_value:
        facts.append(f"R-value {r_value}")
    comfort = spec_value(product, "comfortTemp")
    if comfort:
        facts.append(f"comfort {comfort}")
    price = format_price(product)
    if price != "Price not listed":
        facts.append(price)
    noun = category_count_label(category)
    if facts:
        return truncate_text(
            f"{brand} {model}: {', '.join(facts[:4])}. Compare with other {noun} in a free sortable table."
        )
    return truncate_text(
        f"{brand} {model} specs, weight & price. Official-source data in a free sortable comparison table."
    )


def product_primary_specs(product: dict) -> list[tuple[str, str]]:
    category = product.get("category")
    rows: list[tuple[str, str]] = []
    weight = format_weight(product)
    if weight:
        rows.append(("Weight", weight))
    capacity = format_capacity_display(product) or spec_value(product, "capacity")
    if capacity:
        rows.append(("Capacity", capacity))
    if category == "tent":
        for label, key in (("Structure", "structure"), ("Fabric / Waterproofing", "fabric")):
            value = spec_value(product, key)
            if value:
                rows.append((label, value))
    elif category == "tarp":
        for label, key in (("Type", "tarpType"), ("Size", "size")):
            value = spec_value(product, key)
            if value:
                rows.append((label, value))
    elif category == "sleeping-bag":
        for label, key in (("Type", "bagType"), ("Comfort Rating", "comfortTemp"), ("Fill", "fillType")):
            value = spec_value(product, key)
            if value:
                rows.append((label, value))
    elif category == "sleeping-pad":
        for label, key in (("Type", "padType"), ("R-Value", "rValue"), ("Size", "size"), ("Thickness", "thickness")):
            value = spec_value(product, key)
            if value:
                rows.append((label, value))
    elif category in {"table", "chair"}:
        for label, key in (("Type", "subcategory"), ("Seat Height", "seatHeight"), ("Packed Size", "foldedSize")):
            value = spec_value(product, key)
            if value:
                rows.append((label, value))
    rows.append(("Reference Price", format_price(product)))
    return rows


def product_summary(product: dict, brands: dict[str, dict]) -> str:
    brand_id = product.get("brandId", "")
    brand = brand_display_name(brands.get(brand_id), brand_id)
    model = product.get("model", "")
    category = category_label(product.get("category")).lower()
    facts = []
    weight = format_weight(product)
    if weight:
        facts.append(f"weight {weight}")
    capacity = format_capacity_display(product)
    if capacity:
        facts.append(capacity)
    r_value = spec_value(product, "rValue")
    if r_value:
        facts.append(f"R-value {r_value}")
    comfort = spec_value(product, "comfortTemp")
    if comfort:
        facts.append(f"comfort rating {comfort}")
    price = format_price(product)
    if price != "Price not listed":
        facts.append(f"reference price {price}")
    fact_text = ", ".join(facts[:4])
    if fact_text:
        return (
            f"Compare {brand} {model} specs on CampGear Compare: {fact_text}. "
            "Data is organized from official brand listings for faster side-by-side research."
        )
    return (
        f"Compare {brand} {model} {category} specs on CampGear Compare. "
        "Use the official-source data to check model details before you buy."
    )


def product_highlights(product: dict) -> list[str]:
    description = strip_html(product.get("description", "")).lower()
    highlights = []
    for highlight in product.get("highlights") or []:
        text = strip_html(highlight)
        if not text:
            continue
        snippet = text[:80].lower()
        if description and snippet and snippet in description:
            continue
        if len(text) > 220:
            continue
        if text not in highlights:
            highlights.append(text)
    return highlights[:4]


def page_products(page: dict, products: list[dict]) -> list[dict]:
    categories = page.get("categories") or []
    if not categories:
        return []
    return [p for p in products if p.get("category") in categories]


def sorted_products_for_page(page: dict, products: list[dict], brands: dict[str, dict]) -> list[dict]:
    rows = page_products(page, products)

    def sort_key(product: dict) -> tuple:
        brand = brands.get(product.get("brandId", ""))
        return (brand_rank(brand), (product.get("model") or "").lower())

    return sorted(rows, key=sort_key)


def page_lastmod(page: dict, products: list[dict]) -> str:
    html_path = ROOT / page["file"]
    stamps = [html_path.stat().st_mtime] if html_path.exists() else []
    for product in page_products(page, products):
        brand_id = product.get("brandId")
        if not brand_id:
            continue
        catalog_path = DATA / "official" / brand_id / "products.json"
        if catalog_path.exists():
            stamps.append(catalog_path.stat().st_mtime)
    if not stamps:
        return date.today().isoformat()
    return date.fromtimestamp(max(stamps)).isoformat()


def escape_html(text: object) -> str:
    value = "" if text is None else str(text)
    return (
        value.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def strip_html(text: object) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]*>", " ", str(text or ""))).strip()


def truncate_text(text: object, limit: int = 155) -> str:
    value = strip_html(text)
    if len(value) <= limit:
        return value
    return value[: limit - 1].rsplit(" ", 1)[0].rstrip(" ,.;") + "…"


def category_model_noun(category: str | None) -> str:
    return {
        "tent": "tent",
        "tarp": "tarp",
        "sleeping-bag": "sleeping bag",
        "sleeping-pad": "sleeping pad",
        "stove": "stove",
        "backpack": "backpack",
        "table": "camp table",
        "chair": "camp chair",
    }.get(category or "", "camping gear")


def brand_config(seo: dict) -> dict:
    return seo.get("brand") or {}


def site_domain(seo: dict) -> str:
    url = seo.get("siteUrl", "").rstrip("/")
    domain = url.replace("https://", "").replace("http://", "")
    if domain.startswith("www."):
        domain = domain[4:]
    return domain


def build_organization_node(site_url: str, seo: dict) -> dict:
    site_name = seo.get("siteName", "CampGear Compare")
    brand = brand_config(seo)
    org: dict = {
        "@type": "Organization",
        "@id": f"{site_url}/#organization",
        "name": brand.get("displayName") or site_name,
        "url": f"{site_url}/",
        "logo": f"{site_url}/favicon.svg",
    }
    alternate = brand.get("alternateNames") or []
    if alternate:
        org["alternateName"] = alternate
    description = brand.get("description")
    if description:
        org["description"] = description
    same_as = [u for u in (brand.get("sameAs") or []) if u]
    if same_as:
        org["sameAs"] = same_as
    return org


def build_og_and_twitter(page: dict, site_url: str, seo: dict) -> str:
    title = page["title"]
    description = page["description"]
    url = f"{site_url}{page['path']}"
    image = page.get("ogImage") or seo.get("defaultOgImage") or f"{site_url}/assets/hero-home.png"
    lines = [
        f'<meta property="og:type" content="website" />',
        f'<meta property="og:site_name" content="{escape_html(seo.get("siteName", "CampGear Compare"))}" />',
        f'<meta property="og:title" content="{escape_html(title)}" />',
        f'<meta property="og:description" content="{escape_html(description)}" />',
        f'<meta property="og:url" content="{url}" />',
        f'<meta property="og:image" content="{image}" />',
        f'<meta name="twitter:card" content="summary_large_image" />',
        f'<meta name="twitter:title" content="{escape_html(title)}" />',
        f'<meta name="twitter:description" content="{escape_html(description)}" />',
        f'<meta name="twitter:image" content="{image}" />',
    ]
    if page.get("schema") == "home":
        keywords = brand_config(seo).get("keywords")
        if keywords:
            lines.append(f'<meta name="keywords" content="{escape_html(keywords)}" />')
    return "\n  ".join(lines)


def build_home_schema(site_url: str, seo: dict) -> dict:
    site_name = seo.get("siteName", "CampGear Compare")
    return {
        "@context": "https://schema.org",
        "@graph": [
            build_organization_node(site_url, seo),
            {
                "@type": "WebSite",
                "@id": f"{site_url}/#website",
                "name": site_name,
                "url": f"{site_url}/",
                "publisher": {"@id": f"{site_url}/#organization"},
                "potentialAction": {
                    "@type": "SearchAction",
                    "target": {
                        "@type": "EntryPoint",
                        "urlTemplate": f"{site_url}/tent.html?q={{search_term_string}}",
                    },
                    "query-input": "required name=search_term_string",
                },
            },
        ],
    }


def build_category_schema(
    page: dict,
    site_url: str,
    seo: dict,
    products: list[dict],
    brands: dict[str, dict],
) -> dict:
    page_url = f"{site_url}{page['path']}"
    site_name = seo.get("siteName", "CampGear Compare")
    label = page.get("breadcrumb") or page["file"]
    rows = sorted_products_for_page(page, products, brands)
    brand_names: list[str] = []
    seen: set[str] = set()
    for product in rows:
        brand_id = product.get("brandId")
        if not brand_id or brand_id in seen:
            continue
        seen.add(brand_id)
        brand_names.append(brand_display_name(brands.get(brand_id), brand_id))

    item_elements = []
    for index, product in enumerate(rows[:ITEM_LIST_LIMIT], start=1):
        brand_id = product.get("brandId", "")
        name = f"{brand_display_name(brands.get(brand_id), brand_id)} {product.get('model', '')}".strip()
        item_elements.append(
            {
                "@type": "ListItem",
                "position": index,
                "name": name,
                "url": product_url(site_url, product),
            }
        )

    graph: list[dict] = [
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "name": "Home",
                    "item": f"{site_url}/",
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": label,
                    "item": page_url,
                },
            ],
        },
        {
            "@type": "CollectionPage",
            "name": page["title"],
            "description": page["description"],
            "url": page_url,
            "isPartOf": {"@id": f"{site_url}/#website"},
            "about": {
                "@type": "Thing",
                "name": label,
                "description": (
                    f"{len(rows)} models compared across "
                    + ", ".join(brand_names[:12])
                    + (" and more" if len(brand_names) > 12 else "")
                ),
            },
        },
    ]
    if item_elements:
        graph.append(
            {
                "@type": "ItemList",
                "name": f"{label} compared on {site_name}",
                "numberOfItems": len(rows),
                "itemListElement": item_elements,
            }
        )
    return {"@context": "https://schema.org", "@graph": graph}


def build_legal_schema(page: dict, site_url: str, seo: dict) -> dict:
    return {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": f"{site_url}/",
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": page.get("breadcrumb", "Legal"),
                        "item": f"{site_url}{page['path']}",
                    },
                ],
            },
            {
                "@type": "WebPage",
                "name": page["title"],
                "description": page["description"],
                "url": f"{site_url}{page['path']}",
                "isPartOf": {"@id": f"{site_url}/#website"},
            },
        ],
    }


def build_json_ld(
    page: dict,
    site_url: str,
    seo: dict,
    products: list[dict],
    brands: dict[str, dict],
) -> dict:
    schema = page.get("schema", "")
    if schema == "home":
        return build_home_schema(site_url, seo)
    if schema == "category":
        return build_category_schema(page, site_url, seo, products, brands)
    return build_legal_schema(page, site_url, seo)


def build_seo_head_block(
    page: dict,
    site_url: str,
    seo: dict,
    products: list[dict],
    brands: dict[str, dict],
) -> str:
    json_ld = build_json_ld(page, site_url, seo, products, brands)
    return (
        f"{SEO_HEAD_START}\n"
        f"  {build_og_and_twitter(page, site_url, seo)}\n"
        f'  <script type="application/ld+json">{json.dumps(json_ld, ensure_ascii=False, separators=(",", ":"))}</script>\n'
        f"  {SEO_HEAD_END}"
    )


def build_crawl_paragraph(
    page: dict,
    products: list[dict],
    brands: dict[str, dict],
    seo: dict,
) -> str:
    rows = sorted_products_for_page(page, products, brands)
    if not rows:
        return ""
    label = page.get("breadcrumb") or "Products"
    if label == "Furniture":
        label_plural = "tables and chairs"
    else:
        label_plural = label.lower()
    brand_names: list[str] = []
    seen: set[str] = set()
    for product in rows:
        brand_id = product.get("brandId")
        if not brand_id or brand_id in seen:
            continue
        seen.add(brand_id)
        brand_names.append(brand_display_name(brands.get(brand_id), brand_id))

    sample_models = []
    for product in rows[:8]:
        brand_id = product.get("brandId", "")
        sample_models.append(
            f"{brand_display_name(brands.get(brand_id), brand_id)} {product.get('model', '')}".strip()
        )

    brands_text = ", ".join(brand_names[:14])
    if len(brand_names) > 14:
        brands_text += ", and more"
    samples_text = "; ".join(sample_models)
    brand = brand_config(seo).get("displayName") or seo.get("siteName", "CampGear Compare")
    domain = site_domain(seo)
    return (
        f"{brand} ({domain}) — "
        f"Compare {len(rows)} {label_plural} from {brands_text}. "
        f"Sortable specs include weight, capacity, materials, and reference price. "
        f"Featured models: {samples_text}."
    )


def build_home_crawl_paragraph(seo: dict) -> str:
    brand = brand_config(seo).get("displayName") or seo.get("siteName", "CampGear Compare")
    domain = site_domain(seo)
    return (
        f"{brand} — {domain} · Side-by-side camping gear spec comparisons from official brand data. "
        f"Compare tents, tarps, sleeping bags, and camp furniture."
    )


def build_crawl_links(
    page: dict,
    products: list[dict],
    brands: dict[str, dict],
    seo: dict,
) -> str:
    if page.get("schema") == "home":
        links = [
            ('/tent.html', "Tent comparison"),
            ('/guides/snow-peak-amenity-dome-2-vs-naturehike-cloud-up-2.html', "Amenity Dome 2 vs Cloud Up 2"),
            ('/sleeping-pad.html', "Sleeping pad comparison"),
            ('/sleeping-bag.html', "Sleeping bag comparison"),
            ('/tarp.html', "Tarp comparison"),
            ('/furniture.html', "Camp furniture comparison"),
            ('/stove.html', "Stove comparison"),
            ('/backpack.html', "Backpack comparison"),
        ]
        return (
            '<p class="seo-crawl__links"><strong>Popular comparison hubs:</strong> '
            + " · ".join(
                f'<a href="{escape_html(path)}">{escape_html(label)}</a>' for path, label in links
            )
            + "</p>"
        )

    rows = sorted_products_for_page(page, products, brands)
    if not rows:
        return ""

    product_links = []
    for product in rows[:12]:
        brand_id = product.get("brandId", "")
        label = f"{brand_display_name(brands.get(brand_id), brand_id)} {product.get('model', '')}".strip()
        product_links.append((product_path(product), label))

    brand_links = []
    seen: set[str] = set()
    for product in rows:
        brand_id = product.get("brandId")
        category = product.get("category")
        if not brand_id or not category or brand_id in seen:
            continue
        seen.add(brand_id)
        label = f"{brand_display_name(brands.get(brand_id), brand_id)} {category_label(category).lower()}"
        brand_links.append((brand_category_path(brand_id, category), label))
        if len(brand_links) >= 8:
            break

    blocks = []
    if product_links:
        blocks.append(
            '<p class="seo-crawl__links"><strong>Popular models:</strong> '
            + " · ".join(
                f'<a href="{escape_html(path)}">{escape_html(label)}</a>'
                for path, label in product_links
            )
            + "</p>"
        )
    if brand_links:
        blocks.append(
            '<p class="seo-crawl__links"><strong>Brand pages:</strong> '
            + " · ".join(
                f'<a href="{escape_html(path)}">{escape_html(label)}</a>'
                for path, label in brand_links
            )
            + "</p>"
        )
    return "\n  ".join(blocks)


def build_crawl_block(
    page: dict,
    products: list[dict],
    brands: dict[str, dict],
    seo: dict,
) -> str:
    if page.get("schema") == "home":
        paragraph = build_home_crawl_paragraph(seo)
    else:
        paragraph = build_crawl_paragraph(page, products, brands, seo)
    if not paragraph:
        return ""
    crawl_id = "seo-crawl-home" if page.get("schema") == "home" else "seo-crawl"
    link_html = build_crawl_links(page, products, brands, seo)
    return (
        f"{SEO_CRAWL_START}\n"
        f'  <div class="seo-crawl" id="{crawl_id}">\n'
        f"  <p>{escape_html(paragraph)}</p>\n"
        f"  {link_html}\n"
        f"  </div>\n"
        f"  {SEO_CRAWL_END}"
    )


def sync_html_title_description(text: str, page: dict) -> str:
    title = escape_html(page["title"])
    description = escape_html(page["description"])
    text = re.sub(r"<title>[^<]*</title>", f"<title>{title}</title>", text, count=1)
    text = re.sub(
        r'<meta name="description" content="[^"]*" />',
        f'<meta name="description" content="{description}" />',
        text,
        count=1,
    )
    return text


def inject_html_seo(
    page: dict,
    site_url: str,
    seo: dict,
    products: list[dict],
    brands: dict[str, dict],
) -> bool:
    html_path = ROOT / page["file"]
    if not html_path.exists():
        return False

    text = html_path.read_text(encoding="utf-8")
    text = sync_html_title_description(text, page)
    head_block = build_seo_head_block(page, site_url, seo, products, brands)
    head_pattern = re.compile(re.escape(SEO_HEAD_START) + r".*?" + re.escape(SEO_HEAD_END), re.DOTALL)
    if head_pattern.search(text):
        text = head_pattern.sub(head_block, text, count=1)
    else:
        text = re.sub(
            r'(<link rel="canonical" href="[^"]+" />\n)',
            r"\1  " + head_block + "\n",
            text,
            count=1,
        )

    if page.get("schema") == "category":
        crawl_block = build_crawl_block(page, products, brands, seo)
        if crawl_block:
            crawl_pattern = re.compile(
                re.escape(SEO_CRAWL_START) + r".*?" + re.escape(SEO_CRAWL_END),
                re.DOTALL,
            )
            if crawl_pattern.search(text):
                text = crawl_pattern.sub(crawl_block, text, count=1)
            elif page.get("breadcrumb") == "Furniture":
                text = re.sub(
                    r'(<div id="chairs-matrix"[^>]*></div>\n    </section>)',
                    r"\1\n    " + crawl_block + "\n",
                    text,
                    count=1,
                )
            else:
                text = re.sub(
                    r'(<div id="compare-root"[^>]*></div>)',
                    r"\1\n    " + crawl_block + "\n",
                    text,
                    count=1,
                )

    if page.get("schema") == "home":
        crawl_block = build_crawl_block(page, products, brands, seo)
        if crawl_block:
            crawl_pattern = re.compile(
                re.escape(SEO_CRAWL_START) + r".*?" + re.escape(SEO_CRAWL_END),
                re.DOTALL,
            )
            if crawl_pattern.search(text):
                text = crawl_pattern.sub(crawl_block, text, count=1)
            else:
                text = re.sub(
                    r'(</section>\n\n  <main class="page page--home">)',
                    r"\1\n    " + crawl_block + "\n",
                    text,
                    count=1,
                )

    html_path.write_text(text, encoding="utf-8")
    return True


def static_page_head(title: str, description: str, canonical: str, json_ld: dict, image: str = "") -> str:
    image_meta = (
        f'  <meta property="og:image" content="{escape_html(image)}" />\n'
        f'  <meta name="twitter:image" content="{escape_html(image)}" />\n'
        if image
        else ""
    )
    return (
        "<head>\n"
        '  <meta charset="UTF-8" />\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
        '  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />\n'
        f"  <title>{escape_html(title)}</title>\n"
        f'  <meta name="description" content="{escape_html(description)}" />\n'
        f'  <link rel="canonical" href="{escape_html(canonical)}" />\n'
        '  <meta property="og:type" content="website" />\n'
        '  <meta property="og:site_name" content="CampGear Compare" />\n'
        f'  <meta property="og:title" content="{escape_html(title)}" />\n'
        f'  <meta property="og:description" content="{escape_html(description)}" />\n'
        f'  <meta property="og:url" content="{escape_html(canonical)}" />\n'
        '  <meta name="twitter:card" content="summary_large_image" />\n'
        f'  <meta name="twitter:title" content="{escape_html(title)}" />\n'
        f'  <meta name="twitter:description" content="{escape_html(description)}" />\n'
        f"{image_meta}"
        f'  <script type="application/ld+json">{json.dumps(json_ld, ensure_ascii=False, separators=(",", ":"))}</script>\n'
        '  <script defer data-domain="campgearcompare.com" src="https://plausible.io/js/script.js"></script>\n'
        '  <link rel="preconnect" href="https://fonts.googleapis.com" />\n'
        '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n'
        '  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Noto+Sans+SC:wght@400;500;600;700&family=Permanent+Marker&display=swap" rel="stylesheet" />\n'
        '  <link rel="stylesheet" href="/style.css" />\n'
        "</head>"
    )


def static_header(current_path: str = "") -> str:
    nav_items = [
        ("/index.html", "Home"),
        ("/tent.html", "Tents"),
        ("/tarp.html", "Tarps"),
        ("/furniture.html", "Furniture"),
        ("/sleeping-bag.html", "Sleeping Bags"),
        ("/sleeping-pad.html", "Sleeping Pads"),
        ("/stove.html", "Stoves"),
        ("/backpack.html", "Backpacks"),
        ("/etc.html", "More"),
    ]
    links = []
    for href, label in nav_items:
        current = ' aria-current="page"' if current_path == href else ""
        links.append(f'<li><a href="{href}"{current}>{escape_html(label)}</a></li>')
    return (
        '<header class="site-header">\n'
        '  <nav class="nav" aria-label="Main navigation">\n'
        '    <a class="nav__brand" href="/index.html" aria-label="Back to home">\n'
        '      <span class="nav__logo" aria-hidden="true">\n'
        '        <svg width="28" height="28" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16 4c-4 6-8 10-8 16a8 8 0 1016 0c0-6-4-10-8-16z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/><path d="M16 12v12M12 18h8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>\n'
        "      </span>\n"
        '      <span class="nav__brand-text">CampGear <span class="nav__brand-ai">Compare</span></span>\n'
        "    </a>\n"
        '    <ul class="nav__links nav__links--categories">\n'
        f"      {' '.join(links)}\n"
        "    </ul>\n"
        "  </nav>\n"
        "</header>"
    )


def static_footer() -> str:
    year = date.today().year
    return (
        '<footer class="site-footer">\n'
        '  <div class="site-footer__inner">\n'
        '    <p class="site-footer__brand-url"><a href="https://www.campgearcompare.com/">CampGear Compare</a> · campgearcompare.com</p>\n'
        '    <p class="site-footer__disclaimer">CampGear Compare helps campers compare official product specs side by side. Some links may earn us a commission at no extra cost to you. Specs and images are sourced from brand websites; image copyright belongs to the respective brands.</p>\n'
        '    <nav class="site-footer__legal" aria-label="Legal">\n'
        '      <a href="/legal.html#affiliate">Affiliate Disclosure</a>\n'
        '      <a href="/legal.html#privacy">Privacy</a>\n'
        '      <a href="/legal.html#content-ip">Content &amp; IP</a>\n'
        '      <a href="/legal.html#sponsor">Sponsor Policy</a>\n'
        "    </nav>\n"
        f"    <p class=\"site-footer__copy\">© {year} CampGear Compare · Camping Gear Comparison</p>\n"
        "  </div>\n"
        "</footer>"
    )


def spec_dl_html(specs: list[tuple[str, str]]) -> str:
    return "\n".join(
        f"<div><dt>{escape_html(label)}</dt><dd>{escape_html(value)}</dd></div>"
        for label, value in specs
        if value
    )


def related_products(product: dict, products: list[dict], brands: dict[str, dict], limit: int = 6) -> list[dict]:
    category = product.get("category")
    brand_id = product.get("brandId")
    current_id = product.get("id")
    same_brand = [
        p
        for p in products
        if p.get("id") != current_id and p.get("brandId") == brand_id and p.get("category") == category
    ]
    same_category = [
        p
        for p in products
        if p.get("id") != current_id and p.get("category") == category and p not in same_brand
    ]

    def sort_key(p: dict) -> tuple:
        b = brands.get(p.get("brandId", ""))
        return (brand_rank(b), (p.get("model") or "").lower())

    return sorted(same_brand, key=sort_key)[:limit] + sorted(same_category, key=sort_key)[: max(0, limit - len(same_brand))]


def product_json_ld(product: dict, site_url: str, brands: dict[str, dict]) -> dict:
    brand_id = product.get("brandId", "")
    brand = brand_display_name(brands.get(brand_id), brand_id)
    name = f"{brand} {product.get('model', '')}".strip()
    product_node: dict = {
        "@type": "Product",
        "@id": f"{product_url(site_url, product)}#product",
        "name": name,
        "brand": {"@type": "Brand", "name": brand},
        "category": category_label(product.get("category")),
        "description": product_summary(product, brands),
        "url": product_url(site_url, product),
    }
    if product.get("imageUrl"):
        product_node["image"] = product["imageUrl"]
    price = product.get("priceMin", product.get("price"))
    currency = product.get("currency")
    if price is not None and currency:
        product_node["offers"] = {
            "@type": "Offer",
            "price": price,
            "priceCurrency": currency,
            "availability": "https://schema.org/InStock",
            "url": product.get("sourceUrl") or product_url(site_url, product),
        }
    return {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{site_url}/"},
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": category_label(product.get("category")),
                        "item": f"{site_url}{category_page_path(product.get('category'))}",
                    },
                    {"@type": "ListItem", "position": 3, "name": name, "item": product_url(site_url, product)},
                ],
            },
            product_node,
        ],
    }


def product_page_html(product: dict, products: list[dict], site_url: str, brands: dict[str, dict]) -> str:
    brand_id = product.get("brandId", "")
    brand = brand_display_name(brands.get(brand_id), brand_id)
    model = product.get("model", "")
    category = product.get("category", "")
    name = f"{brand} {model}".strip()
    title = product_page_title(product, brands)
    description = product_meta_description(product, brands)
    canonical = product_url(site_url, product)
    image = product.get("imageUrl") or ""
    specs = product_primary_specs(product)
    related = related_products(product, products, brands)
    official = product.get("sourceUrl") or ""
    official_link = (
        f'<a class="static-button static-button--primary outbound-link" href="{escape_html(official)}" target="_blank" rel="noopener noreferrer">View official source</a>'
        if official
        else ""
    )
    image_html = (
        f'<img src="{escape_html(image)}" alt="{escape_html(product.get("imageAlt") or name)}" width="760" height="570" loading="eager" decoding="async" />'
        if image
        else '<div class="product-modal__no-img">No product image</div>'
    )
    related_html = "\n".join(
        f'<li><a href="{escape_html(product_path(p))}">{escape_html(brand_display_name(brands.get(p.get("brandId", "")), p.get("brandId", "")))} {escape_html(p.get("model", ""))}</a></li>'
        for p in related
    )
    highlights = product_highlights(product)
    highlight_html = "\n".join(f"<li>{escape_html(strip_html(h))}</li>" for h in highlights[:4] if strip_html(h))
    notes = product.get("description") or product_summary(product, brands)
    current_path = category_page_path(category)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        f"{static_page_head(title, description, canonical, product_json_ld(product, site_url, brands), image)}\n"
        '<body data-page="product" data-category="' + escape_html(category) + '">\n'
        f"{static_header(current_path)}\n"
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a>\n'
        f'    <span aria-hidden="true">/</span><a href="{escape_html(current_path)}">{escape_html(category_label(category))}</a>\n'
        f'    <span aria-hidden="true">/</span><span>{escape_html(name)}</span>\n'
        "  </nav>\n"
        '  <article class="static-detail product-detail">\n'
        "    <header class=\"page__head\">\n"
        f'      <p class="page__eyebrow">{escape_html(brand)} · {escape_html(category_label(category))}</p>\n'
        f'      <h1 class="page__title">{escape_html(name)}</h1>\n'
        f'      <p class="page__lead">{escape_html(product_summary(product, brands))}</p>\n'
        f'      <div class="static-actions">{official_link}<a class="static-button" href="{escape_html(current_path)}">Back to comparison table</a></div>\n'
        "    </header>\n"
        '    <div class="product-detail__layout">\n'
        '      <figure class="product-detail__media">\n'
        f"        {image_html}\n"
        f'        <figcaption>Image from {escape_html(brand)} official product listing.</figcaption>\n'
        "      </figure>\n"
        '      <section class="static-panel" aria-labelledby="key-specs">\n'
        '        <h2 id="key-specs">Key Specs</h2>\n'
        f'        <dl class="product-spec">{spec_dl_html(specs)}</dl>\n'
        "      </section>\n"
        "    </div>\n"
        '    <section class="static-panel" aria-labelledby="comparison-notes">\n'
        '      <h2 id="comparison-notes">Comparison Notes</h2>\n'
        f'      <p>{escape_html(strip_html(notes))}</p>\n'
        "    </section>\n"
        + (
            '    <section class="static-panel" aria-labelledby="highlights">\n'
            '      <h2 id="highlights">Highlights</h2>\n'
            f'      <ul class="static-link-list">{highlight_html}</ul>\n'
            "    </section>\n"
            if highlight_html
            else ""
        )
        + (
            '    <section class="static-panel" aria-labelledby="related-models">\n'
            '      <h2 id="related-models">Related Models</h2>\n'
            f'      <ul class="static-link-list">{related_html}</ul>\n'
            "    </section>\n"
            if related_html
            else ""
        )
        + "  </article>\n"
        "</main>\n"
        f"{static_footer()}\n"
        f"{GENERATED_MARKER}\n"
        "</body>\n"
        "</html>\n"
    )


def brand_page_json_ld(
    brand_id: str,
    category: str,
    rows: list[dict],
    site_url: str,
    brands: dict[str, dict],
) -> dict:
    brand = brand_display_name(brands.get(brand_id), brand_id)
    page_url = brand_category_url(site_url, brand_id, category)
    return {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{site_url}/"},
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": category_label(category),
                        "item": f"{site_url}{category_page_path(category)}",
                    },
                    {"@type": "ListItem", "position": 3, "name": f"{brand} {category_label(category)}", "item": page_url},
                ],
            },
            {
                "@type": "CollectionPage",
                "name": f"{brand} {category_label(category)} Specs",
                "description": f"Compare {len(rows)} {brand} {category_model_noun(category)} models by specs and price.",
                "url": page_url,
                "mainEntity": {
                    "@type": "ItemList",
                    "numberOfItems": len(rows),
                    "itemListElement": [
                        {
                            "@type": "ListItem",
                            "position": index,
                            "name": f"{brand} {product.get('model', '')}".strip(),
                            "url": product_url(site_url, product),
                        }
                        for index, product in enumerate(rows, start=1)
                    ],
                },
            },
        ],
    }


def brand_page_html(
    brand_id: str,
    category: str,
    rows: list[dict],
    products: list[dict],
    site_url: str,
    brands: dict[str, dict],
) -> str:
    brand = brand_display_name(brands.get(brand_id), brand_id)
    label = category_label(category)
    title = f"{brand} {label} Comparison — {len(rows)} Models by Weight & Price"
    description = truncate_text(
        f"Compare {len(rows)} {brand} {category_model_noun(category)} models by weight, capacity, materials, and reference price from official brand data."
    )
    canonical = brand_category_url(site_url, brand_id, category)
    current_path = category_page_path(category)
    table_rows = []
    for product in rows:
        specs = dict(product_primary_specs(product))
        table_rows.append(
            "<tr>"
            f'<td><a href="{escape_html(product_path(product))}">{escape_html(product.get("model", ""))}</a></td>'
            f"<td>{escape_html(specs.get('Weight', '—'))}</td>"
            f"<td>{escape_html(specs.get('Capacity') or specs.get('R-Value') or specs.get('Size') or '—')}</td>"
            f"<td>{escape_html(specs.get('Reference Price', '—'))}</td>"
            "</tr>"
        )
    sibling_categories = []
    grouped = defaultdict(int)
    for product in products:
        if product.get("brandId") == brand_id:
            grouped[product.get("category", "")] += 1
    for sibling_category, count in sorted(grouped.items(), key=lambda item: category_label(item[0])):
        if sibling_category != category and count >= MIN_BRAND_CATEGORY_PRODUCTS:
            sibling_categories.append(
                f'<li><a href="{escape_html(brand_category_path(brand_id, sibling_category))}">{escape_html(brand)} {escape_html(category_label(sibling_category))}</a> ({count})</li>'
            )
    sibling_html = "\n".join(sibling_categories)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        f"{static_page_head(title, description, canonical, brand_page_json_ld(brand_id, category, rows, site_url, brands))}\n"
        '<body data-page="brand" data-category="' + escape_html(category) + '">\n'
        f"{static_header(current_path)}\n"
        '<main class="page page--sub static-page">\n'
        '  <nav class="static-breadcrumb" aria-label="Breadcrumb">\n'
        '    <a href="/index.html">Home</a>\n'
        f'    <span aria-hidden="true">/</span><a href="{escape_html(current_path)}">{escape_html(label)}</a>\n'
        f'    <span aria-hidden="true">/</span><span>{escape_html(brand)}</span>\n'
        "  </nav>\n"
        "  <header class=\"page__head\">\n"
        f'    <p class="page__eyebrow">{escape_html(brand)} · {escape_html(label)}</p>\n'
        f'    <h1 class="page__title">{escape_html(brand)} {escape_html(label)} Specs</h1>\n'
        f'    <p class="page__lead">Compare {len(rows)} {escape_html(brand)} {escape_html(category_model_noun(category))} models by key specs and official-source reference prices.</p>\n'
        "  </header>\n"
        '  <section class="static-panel" aria-labelledby="model-table">\n'
        '    <h2 id="model-table">Models</h2>\n'
        '    <div class="table-wrap"><table class="compare-table static-table">\n'
        "      <thead><tr><th>Model</th><th>Weight</th><th>Key Spec</th><th>Price</th></tr></thead>\n"
        f"      <tbody>{''.join(table_rows)}</tbody>\n"
        "    </table></div>\n"
        "  </section>\n"
        + (
            '  <section class="static-panel" aria-labelledby="more-brand-pages">\n'
            '    <h2 id="more-brand-pages">More From This Brand</h2>\n'
            f'    <ul class="static-link-list">{sibling_html}</ul>\n'
            "  </section>\n"
            if sibling_html
            else ""
        )
        + "</main>\n"
        f"{static_footer()}\n"
        f"{GENERATED_MARKER}\n"
        "</body>\n"
        "</html>\n"
    )


def clean_generated_html(directory: Path) -> None:
    if not directory.exists():
        return
    for path in directory.glob("*.html"):
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if GENERATED_MARKER in text:
            path.unlink()


def sorted_visible_products(products: list[dict], brands: dict[str, dict]) -> list[dict]:
    def sort_key(product: dict) -> tuple:
        brand = brands.get(product.get("brandId", ""))
        return (brand_rank(brand), product.get("category", ""), (product.get("model") or "").lower())

    return sorted(products, key=sort_key)


def write_static_pages(site_url: str, products: list[dict], brands: dict[str, dict]) -> list[dict]:
    PRODUCT_DIR.mkdir(exist_ok=True)
    BRAND_DIR.mkdir(exist_ok=True)
    clean_generated_html(PRODUCT_DIR)
    clean_generated_html(BRAND_DIR)

    entries: list[dict] = []
    rows = sorted_visible_products(products, brands)
    for product in rows:
        path = PRODUCT_DIR / f"{product.get('id')}.html"
        path.write_text(product_page_html(product, rows, site_url, brands), encoding="utf-8")
        entries.append(
            {
                "loc": f"{site_url}{product_path(product)}",
                "lastmod": source_lastmod_for_product(product),
                "changefreq": "monthly",
                "priority": "0.6",
            }
        )

    grouped: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for product in rows:
        brand_id = product.get("brandId")
        category = product.get("category")
        if brand_id and category:
            grouped[(brand_id, category)].append(product)

    for (brand_id, category), group in sorted(
        grouped.items(),
        key=lambda item: (brand_rank(brands.get(item[0][0])), category_label(item[0][1])),
    ):
        if len(group) < MIN_BRAND_CATEGORY_PRODUCTS:
            continue
        path = BRAND_DIR / f"{brand_id}-{category}.html"
        group_sorted = sorted(group, key=lambda p: (p.get("model") or "").lower())
        path.write_text(
            brand_page_html(brand_id, category, group_sorted, rows, site_url, brands),
            encoding="utf-8",
        )
        lastmod = max(source_lastmod_for_product(product) for product in group_sorted)
        entries.append(
            {
                "loc": f"{site_url}{brand_category_path(brand_id, category)}",
                "lastmod": lastmod,
                "changefreq": "weekly",
                "priority": "0.7",
            }
        )

    return entries


def write_sitemap(site_url: str, pages: list[dict], products: list[dict], generated_entries: list[dict]) -> None:
    entries = []
    for page in pages:
        loc = f"{site_url}{page['path']}"
        lastmod = page_lastmod(page, products)
        entries.append(
            "  <url>\n"
            f"    <loc>{loc}</loc>\n"
            f"    <lastmod>{lastmod}</lastmod>\n"
            f"    <changefreq>{page['changefreq']}</changefreq>\n"
            f"    <priority>{page['priority']}</priority>\n"
            "  </url>"
        )
    for entry in generated_entries:
        entries.append(
            "  <url>\n"
            f"    <loc>{entry['loc']}</loc>\n"
            f"    <lastmod>{entry['lastmod']}</lastmod>\n"
            f"    <changefreq>{entry['changefreq']}</changefreq>\n"
            f"    <priority>{entry['priority']}</priority>\n"
            "  </url>"
        )
    sitemap = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(entries)
        + "\n</urlset>\n"
    )
    (ROOT / "sitemap.xml").write_text(sitemap, encoding="utf-8")


def write_robots(site_url: str) -> None:
    robots = (
        "User-agent: *\n"
        "Allow: /\n"
        "Allow: /data/catalog.js\n"
        "Allow: /data/brands.json\n"
        "Allow: /data/official/\n"
        "Disallow: /data/products.json\n"
        "\n"
        f"Sitemap: {site_url}/sitemap.xml\n"
    )
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8")


def main() -> int:
    seo = load_json(SEO_PATH)
    site_url = seo["siteUrl"].rstrip("/")
    pages = seo.get("pages", [])
    brands_list = load_json(DATA / "brands.json")
    brands = brand_map(brands_list if isinstance(brands_list, list) else [])
    products = load_official_products()
    generated_entries = write_static_pages(site_url, products, brands)

    write_sitemap(site_url, pages, products, generated_entries)
    write_robots(site_url)

    updated = 0
    for page in pages:
        if inject_html_seo(page, site_url, seo, products, brands):
            updated += 1

    print(
        f"Wrote sitemap.xml and robots.txt for {site_url}; "
        f"generated {len(generated_entries)} static SEO page(s); "
        f"injected SEO blocks into {updated} HTML file(s); "
        f"{len(products)} products indexed for structured data"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
